
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 派系
    /// </summary>
    public enum EItemType
    {
        /// <summary>
        /// 小狗本体
        /// </summary>
        Dog = 1,
        /// <summary>
        /// 小狗头部装饰
        /// </summary>
        Headwear = 2,
        /// <summary>
        /// 小狗眼部装饰
        /// </summary>
        Eyewear = 3,
        /// <summary>
        /// 例如纹身
        /// </summary>
        Arm = 4,
        /// <summary>
        /// 玩家手臂衣服
        /// </summary>
        Clothes = 5,
        /// <summary>
        /// 桌布
        /// </summary>
        Table = 6,
        /// <summary>
        /// 背景
        /// </summary>
        Background = 7,
        /// <summary>
        /// 玩家手部装饰
        /// </summary>
        Accessory = 8,
        /// <summary>
        /// 例如烟酒
        /// </summary>
        Treat = 9,
        /// <summary>
        /// 卡背
        /// </summary>
        CardBack = 10,
        /// <summary>
        /// 卡面
        /// </summary>
        CardFace = 11,
    }

} 

