
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbDogSkin TbDogSkin {get; }
    public TbPayTable TbPayTable {get; }
    public TbGameDevelopConfig TbGameDevelopConfig {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new TbItem(loader("tbitem"));
        TbDogSkin = new TbDogSkin(loader("tbdogskin"));
        TbPayTable = new TbPayTable(loader("tbpaytable"));
        TbGameDevelopConfig = new TbGameDevelopConfig(loader("tbgamedevelopconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbDogSkin.ResolveRef(this);
        TbPayTable.ResolveRef(this);
        TbGameDevelopConfig.ResolveRef(this);
    }
}

}

