
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg
{
public partial class TbPayTable
{
    private readonly System.Collections.Generic.Dictionary<int, PayTable> _dataMap;
    private readonly System.Collections.Generic.List<PayTable> _dataList;
    
    public TbPayTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, PayTable>(count);
        _dataList = new System.Collections.Generic.List<PayTable>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PayTable _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.PayTable.DeserializePayTable(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, PayTable> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PayTable> DataList => _dataList;

    public PayTable GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PayTable Get(int key) => _dataMap[key];
    public PayTable this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

