
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class Achievement : Luban.BeanBase
{
    public Achievement(JSONNode _buf) 
    {
        { if(!_buf["AchievementId"].IsNumber) { throw new SerializationException(); }  AchievementId = _buf["AchievementId"]; }
        { if(!_buf["ApiName"].IsString) { throw new SerializationException(); }  ApiName = _buf["ApiName"]; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
        { if(!_buf["RuleType"].IsNumber) { throw new SerializationException(); }  RuleType = (EAchievementRuleType)_buf["RuleType"].AsInt; }
        { if(!_buf["TargetKey"].IsString) { throw new SerializationException(); }  TargetKey = _buf["TargetKey"]; }
        { if(!_buf["TargetValue"].IsNumber) { throw new SerializationException(); }  TargetValue = _buf["TargetValue"]; }
        { if(!_buf["IsHidden"].IsBoolean) { throw new SerializationException(); }  IsHidden = _buf["IsHidden"]; }
        { if(!_buf["Notes"].IsString) { throw new SerializationException(); }  Notes = _buf["Notes"]; }
        { if(!_buf["SteamNameEn"].IsString) { throw new SerializationException(); }  SteamNameEn = _buf["SteamNameEn"]; }
        { if(!_buf["SteamDescriptionEn"].IsString) { throw new SerializationException(); }  SteamDescriptionEn = _buf["SteamDescriptionEn"]; }
        { if(!_buf["SteamNameZhHans"].IsString) { throw new SerializationException(); }  SteamNameZhHans = _buf["SteamNameZhHans"]; }
        { if(!_buf["SteamDescriptionZhHans"].IsString) { throw new SerializationException(); }  SteamDescriptionZhHans = _buf["SteamDescriptionZhHans"]; }
        { if(!_buf["SteamTitleBriefZhHans"].IsString) { throw new SerializationException(); }  SteamTitleBriefZhHans = _buf["SteamTitleBriefZhHans"]; }
    }

    public static Achievement DeserializeAchievement(JSONNode _buf)
    {
        return new Achievement(_buf);
    }

    /// <summary>
    /// 成就唯一 ID；发布后不可复用
    /// </summary>
    public readonly int AchievementId;
    /// <summary>
    /// 平台和存档使用的稳定机器名；发布后不要改名
    /// </summary>
    public readonly string ApiName;
    /// <summary>
    /// 控制该成就是否参与实际功能。设为 FALSE 时，仅保留 AchievementId 和 ApiName 作为历史墓碑；客户端不再进行条件判定、历史补发、平台读取、解锁或同步，Steam 成就配置转换器也不再导出该行。已停用成就的 AchievementId 和 ApiName 不得复用。<br/>注意：已经为FALSE的条目禁止改回TRUE，如有必要可新增条目
    /// </summary>
    public readonly bool IsEnabled;
    /// <summary>
    /// FirstExternalItemType=首次非初始获得部位；FirstExternalItemRarity=首次非初始获得指定品质；FirstEvent=首次发生事件；StatisticAtLeast=统计达到数值
    /// </summary>
    public readonly EAchievementRuleType RuleType;
    /// <summary>
    /// 由 RuleType 决定含义：部位/品质/事件/PlayerStatistic 的 StatisticKey
    /// </summary>
    public readonly string TargetKey;
    /// <summary>
    /// StatisticAtLeast 的数值门槛；首次类规则填 1
    /// </summary>
    public readonly long TargetValue;
    /// <summary>
    /// 是否在平台/游戏内解锁前隐藏
    /// </summary>
    public readonly bool IsHidden;
    /// <summary>
    /// 填写策划说明或设计约束
    /// </summary>
    public readonly string Notes;
    /// <summary>
    /// Steam 默认英文名称；为空时生成器报错
    /// </summary>
    public readonly string SteamNameEn;
    /// <summary>
    /// Steam 默认英文描述；为空时生成器报错
    /// </summary>
    public readonly string SteamDescriptionEn;
    /// <summary>
    /// Steam 简体中文名称；为空时生成器报错
    /// </summary>
    public readonly string SteamNameZhHans;
    /// <summary>
    /// Steam 简体中文描述；为空时生成器报错
    /// </summary>
    public readonly string SteamDescriptionZhHans;
    /// <summary>
    /// 供其他语言本地化理解标题含义、语气和梗；不在 Steam 直接显示。
    /// </summary>
    public readonly string SteamTitleBriefZhHans;
   
    public const int __ID__ = -879479025;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AchievementId:" + AchievementId + ","
        + "ApiName:" + ApiName + ","
        + "IsEnabled:" + IsEnabled + ","
        + "RuleType:" + RuleType + ","
        + "TargetKey:" + TargetKey + ","
        + "TargetValue:" + TargetValue + ","
        + "IsHidden:" + IsHidden + ","
        + "Notes:" + Notes + ","
        + "SteamNameEn:" + SteamNameEn + ","
        + "SteamDescriptionEn:" + SteamDescriptionEn + ","
        + "SteamNameZhHans:" + SteamNameZhHans + ","
        + "SteamDescriptionZhHans:" + SteamDescriptionZhHans + ","
        + "SteamTitleBriefZhHans:" + SteamTitleBriefZhHans + ","
        + "}";
    }
}
}

