
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class BlindBoxSchedule : Luban.BeanBase
{
    public BlindBoxSchedule(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["NextScheduleId"].IsNumber) { throw new SerializationException(); }  NextScheduleId = _buf["NextScheduleId"]; }
        { if(!_buf["ProgressCheckpoint"].IsNumber) { throw new SerializationException(); }  ProgressCheckpoint = _buf["ProgressCheckpoint"]; }
        { if(!_buf["BlindBoxId"].IsNumber) { throw new SerializationException(); }  BlindBoxId = _buf["BlindBoxId"]; }
        { if(!_buf["FallbackBlindBoxId"].IsNumber) { throw new SerializationException(); }  FallbackBlindBoxId = _buf["FallbackBlindBoxId"]; }
        { if(!_buf["IsLoopTrack"].IsBoolean) { throw new SerializationException(); }  IsLoopTrack = _buf["IsLoopTrack"]; }
        { if(!_buf["StartSeconds"].IsNumber) { throw new SerializationException(); }  StartSeconds = _buf["StartSeconds"]; }
        { if(!_buf["IntervalSeconds"].IsNumber) { throw new SerializationException(); }  IntervalSeconds = _buf["IntervalSeconds"]; }
        { if(!_buf["MaxGrantCount"].IsNumber) { throw new SerializationException(); }  MaxGrantCount = _buf["MaxGrantCount"]; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
        { if(!_buf["SteamPlaytimeGeneratorItemDefId"].IsNumber) { throw new SerializationException(); }  SteamPlaytimeGeneratorItemDefId = _buf["SteamPlaytimeGeneratorItemDefId"]; }
        { if(!_buf["SteamDropIntervalSeconds"].IsNumber) { throw new SerializationException(); }  SteamDropIntervalSeconds = _buf["SteamDropIntervalSeconds"]; }
        { if(!_buf["SteamDropWindowSeconds"].IsNumber) { throw new SerializationException(); }  SteamDropWindowSeconds = _buf["SteamDropWindowSeconds"]; }
        { if(!_buf["SteamDropMaxPerWindow"].IsNumber) { throw new SerializationException(); }  SteamDropMaxPerWindow = _buf["SteamDropMaxPerWindow"]; }
        { if(!_buf["CostChipsOverride"].IsNumber) { throw new SerializationException(); }  CostChipsOverride = _buf["CostChipsOverride"]; }
        { if(!_buf["SteamCompletionReceiptItemDefId"].IsNumber) { throw new SerializationException(); }  SteamCompletionReceiptItemDefId = _buf["SteamCompletionReceiptItemDefId"]; }
    }

    public static BlindBoxSchedule DeserializeBlindBoxSchedule(JSONNode _buf)
    {
        return new BlindBoxSchedule(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 首轮奖励序列中，当前 Schedule 完成后进入的下一条 BlindBoxSchedule.Id；末条首轮 Schedule 填 0，循环 Schedule 填 0；所有启用的首轮 Schedule 必须组成无环、无分叉的单链，顺序不再根据 StartSeconds 或数字 ID 推断。
    /// </summary>
    public readonly int NextScheduleId;
    /// <summary>
    /// 当前 Schedule 正式完成后写入 Steam Stat 的只增进度值；仅首轮奖励序列填写大于 0，循环 Schedule 填 0；沿 NextScheduleId 必须严格递增，发布后不得修改、降低或复用；建议步骤之间预留较大数值间隔，方便以后插入步骤。
    /// </summary>
    public readonly int ProgressCheckpoint;
    /// <summary>
    /// 对应 BlindBox.Id
    /// </summary>
    public readonly int BlindBoxId;
    /// <summary>
    /// FallbackBlindBoxId
    /// </summary>
    public readonly int FallbackBlindBoxId;
    /// <summary>
    /// TRUE 表示正常阶段循环装扮奖励准备行
    /// </summary>
    public readonly bool IsLoopTrack;
    /// <summary>
    /// 客户端用时间，负责展示气球，以及后台提前准备奖励
    /// </summary>
    public readonly int StartSeconds;
    /// <summary>
    /// 非循环行为相对上次领取间隔；循环行为 Steam 直接奖励掉落间隔
    /// </summary>
    public readonly int IntervalSeconds;
    /// <summary>
    /// 最多发放次数；不限填 -1
    /// </summary>
    public readonly int MaxGrantCount;
    /// <summary>
    /// 是否启用
    /// </summary>
    public readonly bool IsEnabled;
    /// <summary>
    /// 通过 TriggerItemDrop 请求的 Steam PlaytimeGenerator ItemDef ID；该定义直接生成最终装扮；本地消耗品填 0
    /// </summary>
    public readonly int SteamPlaytimeGeneratorItemDefId;
    /// <summary>
    /// 当前 PlaytimeGenerator 被预热激活后，正式获得一件奖励所需的 Steam 有效游玩秒数。
    /// </summary>
    public readonly int SteamDropIntervalSeconds;
    /// <summary>
    /// Steam 掉落窗口真实秒数；转换器向上取整为分钟；0 表示不启用
    /// </summary>
    public readonly int SteamDropWindowSeconds;
    /// <summary>
    /// Steam 掉落窗口内最多发放次数；未启用窗口时填 0
    /// </summary>
    public readonly int SteamDropMaxPerWindow;
    /// <summary>
    /// &gt;0 本次展示覆盖 BlindBox 默认筹码成本；=0 表示继承，&lt;0 表示免费并显示其绝对值的字符串并添加删除线，注意配置中的倍率
    /// </summary>
    public readonly int CostChipsOverride;
    /// <summary>
    /// 玩家正式完成并结算该 Schedule 后，由客户端手动授予的 Steam 永久进度回执 ItemDef ID；0 表示不授予
    /// </summary>
    public readonly int SteamCompletionReceiptItemDefId;
   
    public const int __ID__ = -621265139;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "NextScheduleId:" + NextScheduleId + ","
        + "ProgressCheckpoint:" + ProgressCheckpoint + ","
        + "BlindBoxId:" + BlindBoxId + ","
        + "FallbackBlindBoxId:" + FallbackBlindBoxId + ","
        + "IsLoopTrack:" + IsLoopTrack + ","
        + "StartSeconds:" + StartSeconds + ","
        + "IntervalSeconds:" + IntervalSeconds + ","
        + "MaxGrantCount:" + MaxGrantCount + ","
        + "IsEnabled:" + IsEnabled + ","
        + "SteamPlaytimeGeneratorItemDefId:" + SteamPlaytimeGeneratorItemDefId + ","
        + "SteamDropIntervalSeconds:" + SteamDropIntervalSeconds + ","
        + "SteamDropWindowSeconds:" + SteamDropWindowSeconds + ","
        + "SteamDropMaxPerWindow:" + SteamDropMaxPerWindow + ","
        + "CostChipsOverride:" + CostChipsOverride + ","
        + "SteamCompletionReceiptItemDefId:" + SteamCompletionReceiptItemDefId + ","
        + "}";
    }
}
}

