
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class BlindBoxSchedule : Luban.BeanBase
{
    public BlindBoxSchedule(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["BlindBoxId"].IsNumber) { throw new SerializationException(); }  BlindBoxId = _buf["BlindBoxId"]; }
        { if(!_buf["StartSeconds"].IsNumber) { throw new SerializationException(); }  StartSeconds = _buf["StartSeconds"]; }
        { if(!_buf["IntervalSeconds"].IsNumber) { throw new SerializationException(); }  IntervalSeconds = _buf["IntervalSeconds"]; }
        { if(!_buf["EndSeconds"].IsNumber) { throw new SerializationException(); }  EndSeconds = _buf["EndSeconds"]; }
        { if(!_buf["MaxGrantCount"].IsNumber) { throw new SerializationException(); }  MaxGrantCount = _buf["MaxGrantCount"]; }
        { if(!_buf["Priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["Priority"]; }
        { if(!_buf["CanAccumulate"].IsBoolean) { throw new SerializationException(); }  CanAccumulate = _buf["CanAccumulate"]; }
        { if(!_buf["MaxPendingCount"].IsNumber) { throw new SerializationException(); }  MaxPendingCount = _buf["MaxPendingCount"]; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
    }

    public static BlindBoxSchedule DeserializeBlindBoxSchedule(JSONNode _buf)
    {
        return new BlindBoxSchedule(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 对应 BlindBox.Id
    /// </summary>
    public readonly int BlindBoxId;
    /// <summary>
    /// 按玩家总游玩秒数计算的生效时间
    /// </summary>
    public readonly int StartSeconds;
    /// <summary>
    /// 循环间隔；固定时间点填 0
    /// </summary>
    public readonly int IntervalSeconds;
    /// <summary>
    /// 结束时间；无限循环填 -1
    /// </summary>
    public readonly int EndSeconds;
    /// <summary>
    /// 最多发放次数；不限填 -1
    /// </summary>
    public readonly int MaxGrantCount;
    /// <summary>
    /// 开启优先级，数值越大越优先
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 是否允许累积多个待领取资格
    /// </summary>
    public readonly bool CanAccumulate;
    /// <summary>
    /// 最多保留几个待领取资格
    /// </summary>
    public readonly int MaxPendingCount;
    /// <summary>
    /// 是否启用
    /// </summary>
    public readonly bool IsEnabled;
   
    public const int __ID__ = -621265139;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BlindBoxId:" + BlindBoxId + ","
        + "StartSeconds:" + StartSeconds + ","
        + "IntervalSeconds:" + IntervalSeconds + ","
        + "EndSeconds:" + EndSeconds + ","
        + "MaxGrantCount:" + MaxGrantCount + ","
        + "Priority:" + Priority + ","
        + "CanAccumulate:" + CanAccumulate + ","
        + "MaxPendingCount:" + MaxPendingCount + ","
        + "IsEnabled:" + IsEnabled + ","
        + "}";
    }
}
}

