
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class BlindBoxVisual : Luban.BeanBase
{
    public BlindBoxVisual(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["ItemRarity"].IsNumber) { throw new SerializationException(); }  ItemRarity = (ERarity)_buf["ItemRarity"].AsInt; }
        { if(!_buf["BlindBoxSpritePath"].IsString) { throw new SerializationException(); }  BlindBoxSpritePath = _buf["BlindBoxSpritePath"]; }
        { if(!_buf["BlindBoxShadowPath"].IsString) { throw new SerializationException(); }  BlindBoxShadowPath = _buf["BlindBoxShadowPath"]; }
        { if(!_buf["BlindBoxGlowPath"].IsString) { throw new SerializationException(); }  BlindBoxGlowPath = _buf["BlindBoxGlowPath"]; }
        { if(!_buf["BlindBoxBackgroundPath"].IsString) { throw new SerializationException(); }  BlindBoxBackgroundPath = _buf["BlindBoxBackgroundPath"]; }
        { if(!_buf["UpgradeSfxNamePath"].IsString) { throw new SerializationException(); }  UpgradeSfxNamePath = _buf["UpgradeSfxNamePath"]; }
        { if(!_buf["UpgradeEffectPath"].IsString) { throw new SerializationException(); }  UpgradeEffectPath = _buf["UpgradeEffectPath"]; }
    }

    public static BlindBoxVisual DeserializeBlindBoxVisual(JSONNode _buf)
    {
        return new BlindBoxVisual(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 显示名称不会显示在开盲盒环节，但如果游戏中有地方需要显示名字，例如Log，则使用该名字
    /// </summary>
    public readonly string Name;
    public readonly ERarity ItemRarity;
    /// <summary>
    /// 该品质盲盒主体图
    /// </summary>
    public readonly string BlindBoxSpritePath;
    public readonly string BlindBoxShadowPath;
    /// <summary>
    /// 可选
    /// </summary>
    public readonly string BlindBoxGlowPath;
    /// <summary>
    /// 可选
    /// </summary>
    public readonly string BlindBoxBackgroundPath;
    /// <summary>
    /// 开盲盒环节，该品质出现时，播放的音效。<br/>根据约定，音效在游戏后期配置，前期只在控制台打印文字即可。
    /// </summary>
    public readonly string UpgradeSfxNamePath;
    public readonly string UpgradeEffectPath;
   
    public const int __ID__ = 305649974;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "ItemRarity:" + ItemRarity + ","
        + "BlindBoxSpritePath:" + BlindBoxSpritePath + ","
        + "BlindBoxShadowPath:" + BlindBoxShadowPath + ","
        + "BlindBoxGlowPath:" + BlindBoxGlowPath + ","
        + "BlindBoxBackgroundPath:" + BlindBoxBackgroundPath + ","
        + "UpgradeSfxNamePath:" + UpgradeSfxNamePath + ","
        + "UpgradeEffectPath:" + UpgradeEffectPath + ","
        + "}";
    }
}
}

