
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class BlindBoxItemWeight : Luban.BeanBase
{
    public BlindBoxItemWeight(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["BlindBoxId"].IsNumber) { throw new SerializationException(); }  BlindBoxId = _buf["BlindBoxId"]; }
        { if(!_buf["ItemId"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["ItemId"]; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
    }

    public static BlindBoxItemWeight DeserializeBlindBoxItemWeight(JSONNode _buf)
    {
        return new BlindBoxItemWeight(_buf);
    }

    /// <summary>
    /// 稳定且唯一的行ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 对应 BlindBox.Id
    /// </summary>
    public readonly int BlindBoxId;
    /// <summary>
    /// 对应 Item.Id
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 同一盲盒、同一品质内的物品相对权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 关闭后不参与奖池，但保留权重
    /// </summary>
    public readonly bool IsEnabled;
   
    public const int __ID__ = -1542572447;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BlindBoxId:" + BlindBoxId + ","
        + "ItemId:" + ItemId + ","
        + "Weight:" + Weight + ","
        + "IsEnabled:" + IsEnabled + ","
        + "}";
    }
}
}

