
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class BlindBoxRarityRate : Luban.BeanBase
{
    public BlindBoxRarityRate(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["BlindBoxId"].IsNumber) { throw new SerializationException(); }  BlindBoxId = _buf["BlindBoxId"]; }
        { if(!_buf["Rarity"].IsNumber) { throw new SerializationException(); }  Rarity = (ERarity)_buf["Rarity"].AsInt; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
    }

    public static BlindBoxRarityRate DeserializeBlindBoxRarityRate(JSONNode _buf)
    {
        return new BlindBoxRarityRate(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 对应 BlindBox.Id
    /// </summary>
    public readonly int BlindBoxId;
    /// <summary>
    /// 先抽品质时命中的品质
    /// </summary>
    public readonly ERarity Rarity;
    /// <summary>
    /// 品质权重，0 或禁用表示不参与
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 是否启用
    /// </summary>
    public readonly bool IsEnabled;
   
    public const int __ID__ = -554621919;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BlindBoxId:" + BlindBoxId + ","
        + "Rarity:" + Rarity + ","
        + "Weight:" + Weight + ","
        + "IsEnabled:" + IsEnabled + ","
        + "}";
    }
}
}

