
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class BlindBox : Luban.BeanBase
{
    public BlindBox(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["BoxType"].IsNumber) { throw new SerializationException(); }  BoxType = (EBlindBoxType)_buf["BoxType"].AsInt; }
        { if(!_buf["DisplayMode"].IsNumber) { throw new SerializationException(); }  DisplayMode = (EBlindBoxDisplayMode)_buf["DisplayMode"].AsInt; }
        { if(!_buf["CostChips"].IsNumber) { throw new SerializationException(); }  CostChips = _buf["CostChips"]; }
        { if(!_buf["MaxRevealClickCount"].IsNumber) { throw new SerializationException(); }  MaxRevealClickCount = _buf["MaxRevealClickCount"]; }
        { if(!_buf["AutoCollectSeconds"].IsNumber) { throw new SerializationException(); }  AutoCollectSeconds = _buf["AutoCollectSeconds"]; }
        { if(!_buf["IsSteamRequired"].IsBoolean) { throw new SerializationException(); }  IsSteamRequired = _buf["IsSteamRequired"]; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
        { if(!_buf["SteamContainerItemDefId"].IsNumber) { throw new SerializationException(); }  SteamContainerItemDefId = _buf["SteamContainerItemDefId"]; }
        { if(!_buf["SteamGeneratorItemDefId"].IsNumber) { throw new SerializationException(); }  SteamGeneratorItemDefId = _buf["SteamGeneratorItemDefId"]; }
        { if(!_buf["SteamExchangeTargetItemDefId"].IsNumber) { throw new SerializationException(); }  SteamExchangeTargetItemDefId = _buf["SteamExchangeTargetItemDefId"]; }
    }

    public static BlindBox DeserializeBlindBox(JSONNode _buf)
    {
        return new BlindBox(_buf);
    }

    /// <summary>
    /// 唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 策划/显示名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 装扮、新手装扮、消耗品、活动盲盒<br/>程序中硬编码与Item对应列的映射关系
    /// </summary>
    public readonly EBlindBoxType BoxType;
    /// <summary>
    /// 升级表演/直接展示
    /// </summary>
    public readonly EBlindBoxDisplayMode DisplayMode;
    /// <summary>
    /// 基础固定价格，实际需乘以Config表里的倍率来使用
    /// </summary>
    public readonly int CostChips;
    /// <summary>
    /// 装扮盲盒默认 3
    /// </summary>
    public readonly int MaxRevealClickCount;
    /// <summary>
    /// 奖励展示后几秒自动收起
    /// </summary>
    public readonly float AutoCollectSeconds;
    /// <summary>
    /// 装扮 true，消耗品 false
    /// </summary>
    public readonly bool IsSteamRequired;
    /// <summary>
    /// 临时开关
    /// </summary>
    public readonly bool IsEnabled;
    /// <summary>
    /// 现阶段可 0
    /// </summary>
    public readonly int SteamContainerItemDefId;
    /// <summary>
    /// 现阶段可 0
    /// </summary>
    public readonly int SteamGeneratorItemDefId;
    /// <summary>
    /// 现阶段可 0
    /// </summary>
    public readonly int SteamExchangeTargetItemDefId;
   
    public const int __ID__ = -761790890;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "BoxType:" + BoxType + ","
        + "DisplayMode:" + DisplayMode + ","
        + "CostChips:" + CostChips + ","
        + "MaxRevealClickCount:" + MaxRevealClickCount + ","
        + "AutoCollectSeconds:" + AutoCollectSeconds + ","
        + "IsSteamRequired:" + IsSteamRequired + ","
        + "IsEnabled:" + IsEnabled + ","
        + "SteamContainerItemDefId:" + SteamContainerItemDefId + ","
        + "SteamGeneratorItemDefId:" + SteamGeneratorItemDefId + ","
        + "SteamExchangeTargetItemDefId:" + SteamExchangeTargetItemDefId + ","
        + "}";
    }
}
}

