
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class BlindBoxRevealPath : Luban.BeanBase
{
    public BlindBoxRevealPath(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["ActualRarity"].IsNumber) { throw new SerializationException(); }  ActualRarity = (ERarity)_buf["ActualRarity"].AsInt; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
        { if(!_buf["StartRarity"].IsNumber) { throw new SerializationException(); }  StartRarity = (ERarity)_buf["StartRarity"].AsInt; }
        { if(!_buf["MiddleRarity"].IsNumber) { throw new SerializationException(); }  MiddleRarity = (ERarity)_buf["MiddleRarity"].AsInt; }
        { if(!_buf["FinalRarity"].IsNumber) { throw new SerializationException(); }  FinalRarity = (ERarity)_buf["FinalRarity"].AsInt; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
        { if(!_buf["CanEndEarly"].IsBoolean) { throw new SerializationException(); }  CanEndEarly = _buf["CanEndEarly"]; }
    }

    public static BlindBoxRevealPath DeserializeBlindBoxRevealPath(JSONNode _buf)
    {
        return new BlindBoxRevealPath(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 抽奖结果的真实品质
    /// </summary>
    public readonly ERarity ActualRarity;
    /// <summary>
    /// 采用这条演出路径的权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 盒子初始显示品质
    /// </summary>
    public readonly ERarity StartRarity;
    /// <summary>
    /// 点击过程中的中间品质
    /// </summary>
    public readonly ERarity MiddleRarity;
    /// <summary>
    /// 揭晓前最终显示品质
    /// </summary>
    public readonly ERarity FinalRarity;
    /// <summary>
    /// 是否启用
    /// </summary>
    public readonly bool IsEnabled;
    /// <summary>
    /// 达到最高品质后是否提前结束
    /// </summary>
    public readonly bool CanEndEarly;
   
    public const int __ID__ = -624265080;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ActualRarity:" + ActualRarity + ","
        + "Weight:" + Weight + ","
        + "StartRarity:" + StartRarity + ","
        + "MiddleRarity:" + MiddleRarity + ","
        + "FinalRarity:" + FinalRarity + ","
        + "IsEnabled:" + IsEnabled + ","
        + "CanEndEarly:" + CanEndEarly + ","
        + "}";
    }
}
}

