
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class DogReaction : Luban.BeanBase
{
    public DogReaction(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["DogReactionTrigger"].IsNumber) { throw new SerializationException(); }  DogReactionTrigger = (EDogReactionTrigger)_buf["DogReactionTrigger"].AsInt; }
        { if(!_buf["AssetRef"].IsNumber) { throw new SerializationException(); }  AssetRef = (EDogReactionTrigger)_buf["AssetRef"].AsInt; }
        { if(!_buf["EarAsset"].IsString) { throw new SerializationException(); }  EarAsset = _buf["EarAsset"]; }
        { if(!_buf["EyeAsset"].IsString) { throw new SerializationException(); }  EyeAsset = _buf["EyeAsset"]; }
        { if(!_buf["OverrideHeadwear"].IsString) { throw new SerializationException(); }  OverrideHeadwear = _buf["OverrideHeadwear"]; }
        { if(!_buf["WearGlasses"].IsBoolean) { throw new SerializationException(); }  WearGlasses = _buf["WearGlasses"]; }
        { if(!_buf["LeftPawAnimation"].IsString) { throw new SerializationException(); }  LeftPawAnimation = _buf["LeftPawAnimation"]; }
        { if(!_buf["RightPawAnimation"].IsString) { throw new SerializationException(); }  RightPawAnimation = _buf["RightPawAnimation"]; }
        { if(!_buf["TongueAnimation"].IsString) { throw new SerializationException(); }  TongueAnimation = _buf["TongueAnimation"]; }
        { if(!_buf["Notes"].IsString) { throw new SerializationException(); }  Notes = _buf["Notes"]; }
    }

    public static DogReaction DeserializeDogReaction(JSONNode _buf)
    {
        return new DogReaction(_buf);
    }

    public readonly int Id;
    public readonly EDogReactionTrigger DogReactionTrigger;
    /// <summary>
    /// 复用引用枚举所对应的美术资源参数。其自身的值可以Override引用的值
    /// </summary>
    public readonly EDogReactionTrigger AssetRef;
    public readonly string EarAsset;
    public readonly string EyeAsset;
    /// <summary>
    /// 有些表情需要临时更换头饰，例如被打晕的时候头上转的星星。但目前版本没有
    /// </summary>
    public readonly string OverrideHeadwear;
    public readonly bool WearGlasses;
    public readonly string LeftPawAnimation;
    public readonly string RightPawAnimation;
    public readonly string TongueAnimation;
    public readonly string Notes;
   
    public const int __ID__ = -263884955;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DogReactionTrigger:" + DogReactionTrigger + ","
        + "AssetRef:" + AssetRef + ","
        + "EarAsset:" + EarAsset + ","
        + "EyeAsset:" + EyeAsset + ","
        + "OverrideHeadwear:" + OverrideHeadwear + ","
        + "WearGlasses:" + WearGlasses + ","
        + "LeftPawAnimation:" + LeftPawAnimation + ","
        + "RightPawAnimation:" + RightPawAnimation + ","
        + "TongueAnimation:" + TongueAnimation + ","
        + "Notes:" + Notes + ","
        + "}";
    }
}
}

