
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 盲盒类型
    /// </summary>
    public enum EBlindBoxType
    {
        /// <summary>
        /// 装扮盲盒
        /// </summary>
        Decoration = 1,
        /// <summary>
        /// 新手装扮盲盒
        /// </summary>
        NewbieDecoration = 2,
        /// <summary>
        /// 消耗品盲盒
        /// </summary>
        Refreshment = 3,
        /// <summary>
        /// 枚举名字策划请不要轻易改，跟开发人员约定后面加BoxWeight对应Item表的权重
        /// </summary>
        Event = 4,
    }

} 

