
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 盲盒气球提示的数量显示模式
    /// </summary>
    public enum EBlindBoxValueMode
    {
        /// <summary>
        /// 显示消耗筹码数值
        /// </summary>
        Chips = 1,
        /// <summary>
        /// 显示x1
        /// </summary>
        Count = 2,
        /// <summary>
        /// 显示本地化“免费”
        /// </summary>
        Free = 3,
    }

} 

