
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 开盲盒的表演方式
    /// </summary>
    public enum EBlindBoxDisplayMode
    {
        /// <summary>
        /// 三次升级表演
        /// </summary>
        RevealUpgrade = 1,
        /// <summary>
        /// 直接展示奖励
        /// </summary>
        DirectReward = 2,
    }

} 

