
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 狗狗的各种状态枚举
    /// </summary>
    public enum EDogReactionTrigger
    {
        /// <summary>
        /// 特殊处理的方式需要和开发人员约定来定制
        /// </summary>
        Bespoke = 2,
        /// <summary>
        /// 枚举只做分类，具体配置哪些图片需要看具体的表格
        /// </summary>
        Default = 1001,
        /// <summary>
        /// 严肃
        /// </summary>
        Serious = 1002,
        /// <summary>
        /// 无聊
        /// </summary>
        Bored = 1003,
        /// <summary>
        /// 媚眼
        /// </summary>
        Wink = 1004,
        /// <summary>
        /// 兴奋
        /// </summary>
        Excited = 1005,
        /// <summary>
        /// 崇拜
        /// </summary>
        Starstruck = 1006,
        /// <summary>
        /// 沉默
        /// </summary>
        Silent = 1007,
        /// <summary>
        /// 拒绝
        /// </summary>
        Reject = 1008,
        /// <summary>
        /// 等待下注时
        /// </summary>
        WaitingForBet = 2001,
        /// <summary>
        /// 等待玩家选牌
        /// </summary>
        Dealt = 2002,
        /// <summary>
        /// 玩家选牌中等待询问时
        /// </summary>
        WaitingForHint = 2003,
        /// <summary>
        /// 展示询问结果
        /// </summary>
        HintResult = 2004,
        /// <summary>
        /// 得到询问结果后，玩家又更改了选牌
        /// </summary>
        HintExhausted = 2005,
        /// <summary>
        /// 拒绝询问
        /// </summary>
        RefuseHint = 2006,
        /// <summary>
        /// 补牌中
        /// </summary>
        Drawing = 2007,
        /// <summary>
        /// 看到结算结果
        /// </summary>
        Settled = 2008,
        /// <summary>
        /// 看到坏牌
        /// </summary>
        SawNothing = 3001,
        /// <summary>
        /// 看到高对
        /// </summary>
        SawJacksOrBetter = 3002,
        /// <summary>
        /// 看到两对
        /// </summary>
        SawTwoPair = 3003,
        /// <summary>
        /// 看到三条
        /// </summary>
        SawThreeOfAKind = 3004,
        /// <summary>
        /// 看到顺子
        /// </summary>
        SawStraight = 3005,
        /// <summary>
        /// 看到同花
        /// </summary>
        SawFlush = 3006,
        /// <summary>
        /// 看到葫芦
        /// </summary>
        SawFullHouse = 3007,
        /// <summary>
        /// 看到四条
        /// </summary>
        SawFourOfAKind = 3008,
        /// <summary>
        /// 看到同花顺
        /// </summary>
        SawStraightFlush = 3009,
        /// <summary>
        /// 看到皇家同花顺
        /// </summary>
        SawRoyalFlush = 3010,
    }

} 

