
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 牌型
    /// </summary>
    public enum EHandRank
    {
        /// <summary>
        /// 坏牌
        /// </summary>
        Nothing = 1,
        /// <summary>
        /// 一对
        /// </summary>
        OnePair = 2,
        /// <summary>
        /// 两对
        /// </summary>
        TwoPair = 3,
        /// <summary>
        /// 三条
        /// </summary>
        ThreeOfAKind = 4,
        /// <summary>
        /// 顺子
        /// </summary>
        Straight = 5,
        /// <summary>
        /// 同花
        /// </summary>
        Flush = 6,
        /// <summary>
        /// 葫芦
        /// </summary>
        FullHouse = 7,
        /// <summary>
        /// 四条
        /// </summary>
        FourOfAKind = 8,
        /// <summary>
        /// 同花顺
        /// </summary>
        StraightFlush = 9,
        /// <summary>
        /// 皇家同花顺
        /// </summary>
        RoyalFlush = 10,
    }

} 

