
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 在该地区隐藏
    /// </summary>
    [System.Flags]
    public enum EHiddenRegionFlag
    {
        /// <summary>
        /// 在全部国家隐藏
        /// </summary>
        ALL = 1,
        /// <summary>
        /// Saudi Arabia赌博/宗教/酒精/色情/进化论
        /// </summary>
        SA = 2,
        /// <summary>
        /// United Arab Emirates赌博/宗教/酒精/色情
        /// </summary>
        AE = 4,
        /// <summary>
        /// Iran宗教/进化论/赌博/政治/西方文化
        /// </summary>
        IR = 8,
        /// <summary>
        /// Pakistan国家形象/政治
        /// </summary>
        PK = 16,
        /// <summary>
        /// Malaysia赌博/暴力/LGBTQ/酒精
        /// </summary>
        MY = 32,
        /// <summary>
        /// Indonesia赌博/暴力/LGBTQ/酒精
        /// </summary>
        ID = 64,
        /// <summary>
        /// Russia赌博/LGBTQ/极端主义
        /// </summary>
        RU = 128,
        /// <summary>
        /// China赌博/暴力/血腥/色情
        /// </summary>
        CN = 256,
        /// <summary>
        /// North Korea国际制裁/政治
        /// </summary>
        KP = 512,
        /// <summary>
        /// Syria国际制裁/政治/宗教
        /// </summary>
        SY = 1024,
        /// <summary>
        /// Cuba国际制裁/政治
        /// </summary>
        CU = 2048,
    }

} 

