
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// LinkTree 可领取奖励类型
    /// </summary>
    public enum ELinkTreeRewardType
    {
        /// <summary>
        /// 只记录访问/领取状态，不发实际奖励
        /// </summary>
        None = 0,
        /// <summary>
        /// 所有玩家领取相同的 RewardItemId 道具
        /// </summary>
        FixedItem = 1,
        /// <summary>
        /// 所有玩家领取相同数量的 RewardChips 筹码
        /// </summary>
        FixedChips = 2,
        /// <summary>
        /// 按玩家个人领取进度依次发放礼包格子；最后一格可重复兜底，当前预留
        /// </summary>
        SequentialPack = 3,
    }

} 

