
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 玩家统计类型
    /// </summary>
    public enum EPlayerStatisticType
    {
        /// <summary>
        /// 只增累计
        /// </summary>
        Counter = 1,
        /// <summary>
        /// 最高记录
        /// </summary>
        Maximum = 2,
    }

} 

