
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 类型
    /// </summary>
    public enum ERarity
    {
        /// <summary>
        /// 传说
        /// </summary>
        Legendary = 1,
        /// <summary>
        /// 史诗
        /// </summary>
        Epic = 2,
        /// <summary>
        /// 稀有
        /// </summary>
        Rare = 3,
        /// <summary>
        /// 普通
        /// </summary>
        Common = 4,
        /// <summary>
        /// 渠道奖励，不按传统系统度计算
        /// </summary>
        Special1 = 5,
        /// <summary>
        /// 渠道奖励，不按传统系统度计算
        /// </summary>
        Special2 = 6,
    }

} 

