
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 物品稀有度
    /// </summary>
    public enum ERarity
    {
        /// <summary>
        /// 普通
        /// </summary>
        Common = 6,
        /// <summary>
        /// 优秀
        /// </summary>
        Uncommon = 5,
        /// <summary>
        /// 稀有
        /// </summary>
        Rare = 4,
        /// <summary>
        /// 史诗
        /// </summary>
        Epic = 3,
        /// <summary>
        /// 传说
        /// </summary>
        Legendary = 2,
        /// <summary>
        /// 神话
        /// </summary>
        Mythic = 1,
        /// <summary>
        /// 渠道奖励，不按传统系统度计算
        /// </summary>
        Special1 = 21,
        /// <summary>
        /// 渠道奖励，不按传统系统度计算
        /// </summary>
        Special2 = 22,
    }

} 

