
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// Steam定义的物品类型
    /// </summary>
    public enum ESteamItemDefType
    {
        /// <summary>
        /// 这个显式枚举值可能会变，到时候会改成Steam要求的枚举值，因此使用时不要根据int值来判断
        /// </summary>
        Item = 1,
    }

} 

