
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class GameDevelopConfig : Luban.BeanBase
{
    public GameDevelopConfig(JSONNode _buf) 
    {
        { if(!_buf["BlindBoxWaitDurationMultiplier"].IsNumber) { throw new SerializationException(); }  BlindBoxWaitDurationMultiplier = _buf["BlindBoxWaitDurationMultiplier"]; }
        { if(!_buf["BlindBoxCostScale"].IsNumber) { throw new SerializationException(); }  BlindBoxCostScale = _buf["BlindBoxCostScale"]; }
        { if(!_buf["PlayerStatisticScale"].IsNumber) { throw new SerializationException(); }  PlayerStatisticScale = _buf["PlayerStatisticScale"]; }
        { if(!_buf["BlindBoxLoopIntervalSeconds"].IsNumber) { throw new SerializationException(); }  BlindBoxLoopIntervalSeconds = _buf["BlindBoxLoopIntervalSeconds"]; }
        { if(!_buf["LinkTreeVisibleBannerCount"].IsNumber) { throw new SerializationException(); }  LinkTreeVisibleBannerCount = _buf["LinkTreeVisibleBannerCount"]; }
        { if(!_buf["SteamPlaytimeDropLeadSeconds"].IsNumber) { throw new SerializationException(); }  SteamPlaytimeDropLeadSeconds = _buf["SteamPlaytimeDropLeadSeconds"]; }
        { if(!_buf["SteamPlaytimeRequestLeadSeconds"].IsNumber) { throw new SerializationException(); }  SteamPlaytimeRequestLeadSeconds = _buf["SteamPlaytimeRequestLeadSeconds"]; }
        { if(!_buf["BlindBoxLoopSteamVoucherInventoryLimit"].IsNumber) { throw new SerializationException(); }  BlindBoxLoopSteamVoucherInventoryLimit = _buf["BlindBoxLoopSteamVoucherInventoryLimit"]; }
        { if(!_buf["ProactiveInteractionHintIdleSeconds"].IsNumber) { throw new SerializationException(); }  ProactiveInteractionHintIdleSeconds = _buf["ProactiveInteractionHintIdleSeconds"]; }
    }

    public static GameDevelopConfig DeserializeGameDevelopConfig(JSONNode _buf)
    {
        return new GameDevelopConfig(_buf);
    }

    /// <summary>
    /// 等待盲盒时间倍率
    /// </summary>
    public readonly float BlindBoxWaitDurationMultiplier;
    /// <summary>
    /// 盲盒消耗倍率
    /// </summary>
    public readonly float BlindBoxCostScale;
    /// <summary>
    /// 统计倍率
    /// </summary>
    public readonly float PlayerStatisticScale;
    /// <summary>
    /// 正常阶段盲盒展示间隔
    /// </summary>
    public readonly float BlindBoxLoopIntervalSeconds;
    /// <summary>
    /// LinkTree最佳显示条目数量
    /// </summary>
    public readonly int LinkTreeVisibleBannerCount;
    /// <summary>
    /// Steam提前准备盲盒的秒数
    /// </summary>
    public readonly int SteamPlaytimeDropLeadSeconds;
    /// <summary>
    /// Steam掉落请求提前秒数
    /// </summary>
    public readonly int SteamPlaytimeRequestLeadSeconds;
    /// <summary>
    /// 循环Steam盲盒券库存上限
    /// </summary>
    public readonly int BlindBoxLoopSteamVoucherInventoryLimit;
    /// <summary>
    /// 新手操作提示等待时间
    /// </summary>
    public readonly int ProactiveInteractionHintIdleSeconds;
   
    public const int __ID__ = -780791539;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BlindBoxWaitDurationMultiplier:" + BlindBoxWaitDurationMultiplier + ","
        + "BlindBoxCostScale:" + BlindBoxCostScale + ","
        + "PlayerStatisticScale:" + PlayerStatisticScale + ","
        + "BlindBoxLoopIntervalSeconds:" + BlindBoxLoopIntervalSeconds + ","
        + "LinkTreeVisibleBannerCount:" + LinkTreeVisibleBannerCount + ","
        + "SteamPlaytimeDropLeadSeconds:" + SteamPlaytimeDropLeadSeconds + ","
        + "SteamPlaytimeRequestLeadSeconds:" + SteamPlaytimeRequestLeadSeconds + ","
        + "BlindBoxLoopSteamVoucherInventoryLimit:" + BlindBoxLoopSteamVoucherInventoryLimit + ","
        + "ProactiveInteractionHintIdleSeconds:" + ProactiveInteractionHintIdleSeconds + ","
        + "}";
    }
}
}

