
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class InteractionHintConfig : Luban.BeanBase
{
    public InteractionHintConfig(JSONNode _buf) 
    {
        { if(!_buf["Key"].IsString) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["ProactiveEnabled"].IsBoolean) { throw new SerializationException(); }  ProactiveEnabled = _buf["ProactiveEnabled"]; }
        { if(!_buf["ProactiveIdleSeconds"].IsNumber) { throw new SerializationException(); }  ProactiveIdleSeconds = _buf["ProactiveIdleSeconds"]; }
        { if(!_buf["ProactiveRepeatSeconds"].IsNumber) { throw new SerializationException(); }  ProactiveRepeatSeconds = _buf["ProactiveRepeatSeconds"]; }
        { if(!_buf["Priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["Priority"]; }
    }

    public static InteractionHintConfig DeserializeInteractionHintConfig(JSONNode _buf)
    {
        return new InteractionHintConfig(_buf);
    }

    /// <summary>
    /// 唯一配置键
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 中文说明
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 是否启用主动提示
    /// </summary>
    public readonly bool ProactiveEnabled;
    /// <summary>
    /// 首次主动提示前的无操作等待秒数
    /// </summary>
    public readonly float ProactiveIdleSeconds;
    /// <summary>
    /// 提示播放完后再次提示前的等待秒数，0表示不重复
    /// </summary>
    public readonly float ProactiveRepeatSeconds;
    /// <summary>
    /// 多个提示同时可用时数值越高越优先
    /// </summary>
    public readonly int Priority;
   
    public const int __ID__ = 380180539;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "Description:" + Description + ","
        + "ProactiveEnabled:" + ProactiveEnabled + ","
        + "ProactiveIdleSeconds:" + ProactiveIdleSeconds + ","
        + "ProactiveRepeatSeconds:" + ProactiveRepeatSeconds + ","
        + "Priority:" + Priority + ","
        + "}";
    }
}
}

