
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["ItemType"].IsNumber) { throw new SerializationException(); }  ItemType = (EItemType)_buf["ItemType"].AsInt; }
        { if(!_buf["Rarity"].IsNumber) { throw new SerializationException(); }  Rarity = (ERarity)_buf["Rarity"].AsInt; }
        { if(!_buf["SortOrder"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["SortOrder"]; }
        { if(!_buf["BlindBoxWeight"].IsNumber) { throw new SerializationException(); }  BlindBoxWeight = _buf["BlindBoxWeight"]; }
        { if(!_buf["IsUnique"].IsBoolean) { throw new SerializationException(); }  IsUnique = _buf["IsUnique"]; }
        { if(!_buf["HiddenRegionFlag"].IsNumber) { throw new SerializationException(); }  HiddenRegionFlag = (EHiddenRegionFlag)_buf["HiddenRegionFlag"].AsInt; }
        { if(!_buf["SafeResourceId"].IsNumber) { throw new SerializationException(); }  SafeResourceId = _buf["SafeResourceId"]; }
        { if(!_buf["BlindBoxId"].IsNumber) { throw new SerializationException(); }  BlindBoxId = _buf["BlindBoxId"]; }
        { var __json0 = _buf["AssetPathList"]; if(!__json0.IsArray) { throw new SerializationException(); } AssetPathList = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  AssetPathList.Add(__v0); }   }
        { if(!_buf["IconPath"].IsString) { throw new SerializationException(); }  IconPath = _buf["IconPath"]; }
        { if(!_buf["SkinId"].IsNumber) { throw new SerializationException(); }  SkinId = _buf["SkinId"]; }
    }

    public static Item DeserializeItem(JSONNode _buf)
    {
        return new Item(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly EItemType ItemType;
    public readonly ERarity Rarity;
    /// <summary>
    /// 排序权重，数字越大约靠前
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 盲盒权重
    /// </summary>
    public readonly int BlindBoxWeight;
    /// <summary>
    /// 非唯一的物品可以重复获得
    /// </summary>
    public readonly bool IsUnique;
    /// <summary>
    /// 在哪些国家无法抽到
    /// </summary>
    public readonly EHiddenRegionFlag HiddenRegionFlag;
    /// <summary>
    /// 直播模式或者安全模式开启状态下，需要替换成和谐资源，该替换规则高于国家规则
    /// </summary>
    public readonly int SafeResourceId;
    /// <summary>
    /// 所属盲盒的id，相同id的物品在同一个组里进行随机
    /// </summary>
    public readonly int BlindBoxId;
    /// <summary>
    /// 由于部件拆的比较碎，因此需要文件夹路径如 `Assets\Eyewear\EyePatch.png`<br/>拿到字符串后需要自行转义<br/>该字段为列表，可以跨行填写多个<br/>要注意，也可以是tres文件<br/>由于小狗皮肤由多个文件组成，因此直接填写文件夹目录
    /// </summary>
    public readonly System.Collections.Generic.List<string> AssetPathList;
    /// <summary>
    /// 在背包内显示的图标
    /// </summary>
    public readonly string IconPath;
    public readonly int SkinId;
   
    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "ItemType:" + ItemType + ","
        + "Rarity:" + Rarity + ","
        + "SortOrder:" + SortOrder + ","
        + "BlindBoxWeight:" + BlindBoxWeight + ","
        + "IsUnique:" + IsUnique + ","
        + "HiddenRegionFlag:" + HiddenRegionFlag + ","
        + "SafeResourceId:" + SafeResourceId + ","
        + "BlindBoxId:" + BlindBoxId + ","
        + "AssetPathList:" + Luban.StringUtil.CollectionToString(AssetPathList) + ","
        + "IconPath:" + IconPath + ","
        + "SkinId:" + SkinId + ","
        + "}";
    }
}
}

