
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class PlayerStatistic : Luban.BeanBase
{
    public PlayerStatistic(JSONNode _buf) 
    {
        { if(!_buf["StatisticId"].IsNumber) { throw new SerializationException(); }  StatisticId = _buf["StatisticId"]; }
        { if(!_buf["StatisticKey"].IsString) { throw new SerializationException(); }  StatisticKey = _buf["StatisticKey"]; }
        { if(!_buf["DisplayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["DisplayName"]; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
        { if(!_buf["Unit"].IsNumber) { throw new SerializationException(); }  Unit = (EPlayerStatisticUnit)_buf["Unit"].AsInt; }
        { if(!_buf["StatisticType"].IsNumber) { throw new SerializationException(); }  StatisticType = (EPlayerStatisticType)_buf["StatisticType"].AsInt; }
        { if(!_buf["PlatformApiName"].IsString) { throw new SerializationException(); }  PlatformApiName = _buf["PlatformApiName"]; }
        { if(!_buf["SyncToPlatform"].IsBoolean) { throw new SerializationException(); }  SyncToPlatform = _buf["SyncToPlatform"]; }
        { if(!_buf["Notes"].IsString) { throw new SerializationException(); }  Notes = _buf["Notes"]; }
    }

    public static PlayerStatistic DeserializePlayerStatistic(JSONNode _buf)
    {
        return new PlayerStatistic(_buf);
    }

    /// <summary>
    /// 表内稳定数字 ID；发布后不可复用
    /// </summary>
    public readonly int StatisticId;
    /// <summary>
    /// 游戏内部、Achievement.TargetKey 和数据导出共用的稳定机器名
    /// </summary>
    public readonly string StatisticKey;
    /// <summary>
    /// CSV 数据字典用的中文名称
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 控制该统计定义是否参与实际功能。设为 FALSE 时，仅保留 StatisticId、StatisticKey 和 PlatformApiName 作为历史墓碑；客户端不再累计、显示、用于成就判定或参与平台同步，Steam统计配置转换器也不再导出。玩家存档中已有的历史统计值可以保留，但运行时忽略。已停用统计的 StatisticId、StatisticKey 和 PlatformApiName 不得复用。<br/><br/>注意：已经为FALSE的条目禁止改回TRUE，如有必要可新增条目
    /// </summary>
    public readonly bool IsEnabled;
    /// <summary>
    /// 数值单位
    /// </summary>
    public readonly EPlayerStatisticUnit Unit;
    /// <summary>
    /// Counter=只增累计；Maximum=仅保留最高值
    /// </summary>
    public readonly EPlayerStatisticType StatisticType;
    /// <summary>
    /// 未来 Steam/其他平台使用的机器名；发布后不要改名
    /// </summary>
    public readonly string PlatformApiName;
    /// <summary>
    /// 未来是否同步到平台统计
    /// </summary>
    public readonly bool SyncToPlatform;
    /// <summary>
    /// 最重要的统计口径；Debug 行为不应改变任何正式统计
    /// </summary>
    public readonly string Notes;
   
    public const int __ID__ = -485334193;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "StatisticId:" + StatisticId + ","
        + "StatisticKey:" + StatisticKey + ","
        + "DisplayName:" + DisplayName + ","
        + "IsEnabled:" + IsEnabled + ","
        + "Unit:" + Unit + ","
        + "StatisticType:" + StatisticType + ","
        + "PlatformApiName:" + PlatformApiName + ","
        + "SyncToPlatform:" + SyncToPlatform + ","
        + "Notes:" + Notes + ","
        + "}";
    }
}
}

