
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class RarityUI : Luban.BeanBase
{
    public RarityUI(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["ItemRarity"].IsNumber) { throw new SerializationException(); }  ItemRarity = (ERarity)_buf["ItemRarity"].AsInt; }
        { if(!_buf["FrameAssetPath"].IsString) { throw new SerializationException(); }  FrameAssetPath = _buf["FrameAssetPath"]; }
        { if(!_buf["PlateAssetPath"].IsString) { throw new SerializationException(); }  PlateAssetPath = _buf["PlateAssetPath"]; }
    }

    public static RarityUI DeserializeRarityUI(JSONNode _buf)
    {
        return new RarityUI(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly ERarity ItemRarity;
    public readonly string FrameAssetPath;
    public readonly string PlateAssetPath;
   
    public const int __ID__ = 434338207;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "ItemRarity:" + ItemRarity + ","
        + "FrameAssetPath:" + FrameAssetPath + ","
        + "PlateAssetPath:" + PlateAssetPath + ","
        + "}";
    }
}
}

