
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class RefreshmentConfig : Luban.BeanBase
{
    public RefreshmentConfig(JSONNode _buf) 
    {
        { if(!_buf["ItemId"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["ItemId"]; }
        ItemId_Ref = null;
        { if(!_buf["DurationHands"].IsNumber) { throw new SerializationException(); }  DurationHands = _buf["DurationHands"]; }
        { if(!_buf["LuckyDealMode"].IsNumber) { throw new SerializationException(); }  LuckyDealMode = (ELuckyDealMode)_buf["LuckyDealMode"].AsInt; }
        { if(!_buf["LuckyDealTriggerChance"].IsNumber) { throw new SerializationException(); }  LuckyDealTriggerChance = _buf["LuckyDealTriggerChance"]; }
        { if(!_buf["InteractionHintSfxCue"].IsString) { throw new SerializationException(); }  InteractionHintSfxCue = _buf["InteractionHintSfxCue"]; }
        { if(!_buf["UseSfxCue"].IsString) { throw new SerializationException(); }  UseSfxCue = _buf["UseSfxCue"]; }
        { if(!_buf["BalloonOffsetY"].IsNumber) { throw new SerializationException(); }  BalloonOffsetY = _buf["BalloonOffsetY"]; }
    }

    public static RefreshmentConfig DeserializeRefreshmentConfig(JSONNode _buf)
    {
        return new RefreshmentConfig(_buf);
    }

    /// <summary>
    /// 关联 `Item.Id` 的唯一配置。仅允许填写 `ItemType = Refreshment` 的物品；
    /// </summary>
    public readonly int ItemId;
    public Item ItemId_Ref;
    /// <summary>
    /// 使用成功后获得的 BUFF 持续牌局数。每次成功下注并开始新局时消耗 1 局；建议填写 1-99。
    /// </summary>
    public readonly int DurationHands;
    /// <summary>
    /// 决定幸运发牌的具体规则。第一版只支持 `GuidedDraw`；其他枚举为后续预留，暂勿配置。
    /// </summary>
    public readonly ELuckyDealMode LuckyDealMode;
    /// <summary>
    /// BUFF 生效期间，每局开始时触发幸运发牌的概率。填写 0-1 小数，例如 `0.75` 表示 75%；未触发也会消耗该局。
    /// </summary>
    public readonly float LuckyDealTriggerChance;
    /// <summary>
    /// 点击桌面 Refreshment 时，播放交互提示动画所用的 AudioManager 逻辑 Cue。填空则静音；不要填写文件扩展名或资源路径。
    /// </summary>
    public readonly string InteractionHintSfxCue;
    /// <summary>
    /// 玩家确认使用 Refreshment 并激活 BUFF 时播放的 AudioManager 逻辑 Cue。可按饮品/食物/器具分别配置；填空则静音。
    /// </summary>
    public readonly string UseSfxCue;
    /// <summary>
    /// 在 PSD 导出定位的基础上，对 UseBalloon 和 StatusBalloon 同时追加的 Y 轴像素偏移。正数向下、负数向上；例如热气使气球偏高时填写正数。
    /// </summary>
    public readonly int BalloonOffsetY;
   
    public const int __ID__ = -661994693;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ItemId_Ref = tables.TbItem.GetOrDefault(ItemId);
    }

    public override string ToString()
    {
        return "{ "
        + "ItemId:" + ItemId + ","
        + "DurationHands:" + DurationHands + ","
        + "LuckyDealMode:" + LuckyDealMode + ","
        + "LuckyDealTriggerChance:" + LuckyDealTriggerChance + ","
        + "InteractionHintSfxCue:" + InteractionHintSfxCue + ","
        + "UseSfxCue:" + UseSfxCue + ","
        + "BalloonOffsetY:" + BalloonOffsetY + ","
        + "}";
    }
}
}

