
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class SteamItemDefIdRange : Luban.BeanBase
{
    public SteamItemDefIdRange(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["StartItemDefId"].IsNumber) { throw new SerializationException(); }  StartItemDefId = _buf["StartItemDefId"]; }
        { if(!_buf["EndItemDefId"].IsNumber) { throw new SerializationException(); }  EndItemDefId = _buf["EndItemDefId"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["Purpose"].IsString) { throw new SerializationException(); }  Purpose = _buf["Purpose"]; }
        { if(!_buf["Example"].IsString) { throw new SerializationException(); }  Example = _buf["Example"]; }
    }

    public static SteamItemDefIdRange DeserializeSteamItemDefIdRange(JSONNode _buf)
    {
        return new SteamItemDefIdRange(_buf);
    }

    public readonly int Id;
    public readonly int StartItemDefId;
    public readonly int EndItemDefId;
    public readonly string Description;
    public readonly string Purpose;
    public readonly string Example;
   
    public const int __ID__ = -1017618976;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "StartItemDefId:" + StartItemDefId + ","
        + "EndItemDefId:" + EndItemDefId + ","
        + "Description:" + Description + ","
        + "Purpose:" + Purpose + ","
        + "Example:" + Example + ","
        + "}";
    }
}
}

