
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class TabGroup : Luban.BeanBase
{
    public TabGroup(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["TabName"].IsString) { throw new SerializationException(); }  TabName = _buf["TabName"]; }
        { var __json0 = _buf["TabItemTypeList"]; if(!__json0.IsArray) { throw new SerializationException(); } TabItemTypeList = new System.Collections.Generic.List<EItemType>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { EItemType __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (EItemType)__e0.AsInt; }  TabItemTypeList.Add(__v0); }   }
        { if(!_buf["SortOrder"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["SortOrder"]; }
    }

    public static TabGroup DeserializeTabGroup(JSONNode _buf)
    {
        return new TabGroup(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 显示名称
    /// </summary>
    public readonly string TabName;
    /// <summary>
    /// 包含类型
    /// </summary>
    public readonly System.Collections.Generic.List<EItemType> TabItemTypeList;
    /// <summary>
    /// 在标签栏的顺序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -864542710;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TabName:" + TabName + ","
        + "TabItemTypeList:" + Luban.StringUtil.CollectionToString(TabItemTypeList) + ","
        + "SortOrder:" + SortOrder + ","
        + "}";
    }
}
}

