
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace DataTables
{
public partial class Tables
{
    public TbDogSkin TbDogSkin {get; }
    public TbPayTable TbPayTable {get; }
    public TbGameDevelopConfig TbGameDevelopConfig {get; }
    public TbRarityUI TbRarityUI {get; }
    public TbDogReaction TbDogReaction {get; }
    public TbDesktopActivityState TbDesktopActivityState {get; }
    public TbBGMList TbBGMList {get; }
    public TbAchievement TbAchievement {get; }
    public TbPlayerStatistic TbPlayerStatistic {get; }
    public TbItem TbItem {get; }
    public TbTabGroup TbTabGroup {get; }
    public TbEquipmentSlotConfig TbEquipmentSlotConfig {get; }
    public TbBlindBox TbBlindBox {get; }
    public TbBlindBoxSchedule TbBlindBoxSchedule {get; }
    public TbBlindBoxRarityRate TbBlindBoxRarityRate {get; }
    public TbBlindBoxRevealPath TbBlindBoxRevealPath {get; }
    public TbBlindBoxVisual TbBlindBoxVisual {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbDogSkin = new TbDogSkin(loader("tbdogskin"));
        TbPayTable = new TbPayTable(loader("tbpaytable"));
        TbGameDevelopConfig = new TbGameDevelopConfig(loader("tbgamedevelopconfig"));
        TbRarityUI = new TbRarityUI(loader("tbrarityui"));
        TbDogReaction = new TbDogReaction(loader("tbdogreaction"));
        TbDesktopActivityState = new TbDesktopActivityState(loader("tbdesktopactivitystate"));
        TbBGMList = new TbBGMList(loader("tbbgmlist"));
        TbAchievement = new TbAchievement(loader("tbachievement"));
        TbPlayerStatistic = new TbPlayerStatistic(loader("tbplayerstatistic"));
        TbItem = new TbItem(loader("tbitem"));
        TbTabGroup = new TbTabGroup(loader("tbtabgroup"));
        TbEquipmentSlotConfig = new TbEquipmentSlotConfig(loader("tbequipmentslotconfig"));
        TbBlindBox = new TbBlindBox(loader("tbblindbox"));
        TbBlindBoxSchedule = new TbBlindBoxSchedule(loader("tbblindboxschedule"));
        TbBlindBoxRarityRate = new TbBlindBoxRarityRate(loader("tbblindboxrarityrate"));
        TbBlindBoxRevealPath = new TbBlindBoxRevealPath(loader("tbblindboxrevealpath"));
        TbBlindBoxVisual = new TbBlindBoxVisual(loader("tbblindboxvisual"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbDogSkin.ResolveRef(this);
        TbPayTable.ResolveRef(this);
        TbGameDevelopConfig.ResolveRef(this);
        TbRarityUI.ResolveRef(this);
        TbDogReaction.ResolveRef(this);
        TbDesktopActivityState.ResolveRef(this);
        TbBGMList.ResolveRef(this);
        TbAchievement.ResolveRef(this);
        TbPlayerStatistic.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbTabGroup.ResolveRef(this);
        TbEquipmentSlotConfig.ResolveRef(this);
        TbBlindBox.ResolveRef(this);
        TbBlindBoxSchedule.ResolveRef(this);
        TbBlindBoxRarityRate.ResolveRef(this);
        TbBlindBoxRevealPath.ResolveRef(this);
        TbBlindBoxVisual.ResolveRef(this);
    }
}

}

