
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace DataTables
{
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbDogSkin TbDogSkin {get; }
    public TbPayTable TbPayTable {get; }
    public TbGameDevelopConfig TbGameDevelopConfig {get; }
    public TbRarityUI TbRarityUI {get; }
    public TbTabGroup TbTabGroup {get; }
    public TbDogReaction TbDogReaction {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new TbItem(loader("tbitem"));
        TbDogSkin = new TbDogSkin(loader("tbdogskin"));
        TbPayTable = new TbPayTable(loader("tbpaytable"));
        TbGameDevelopConfig = new TbGameDevelopConfig(loader("tbgamedevelopconfig"));
        TbRarityUI = new TbRarityUI(loader("tbrarityui"));
        TbTabGroup = new TbTabGroup(loader("tbtabgroup"));
        TbDogReaction = new TbDogReaction(loader("tbdogreaction"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbDogSkin.ResolveRef(this);
        TbPayTable.ResolveRef(this);
        TbGameDevelopConfig.ResolveRef(this);
        TbRarityUI.ResolveRef(this);
        TbTabGroup.ResolveRef(this);
        TbDogReaction.ResolveRef(this);
    }
}

}

