
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbBlindBoxItemWeight
{
    private readonly System.Collections.Generic.Dictionary<int, BlindBoxItemWeight> _dataMap;
    private readonly System.Collections.Generic.List<BlindBoxItemWeight> _dataList;
    
    public TbBlindBoxItemWeight(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BlindBoxItemWeight>(count);
        _dataList = new System.Collections.Generic.List<BlindBoxItemWeight>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BlindBoxItemWeight _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.BlindBoxItemWeight.DeserializeBlindBoxItemWeight(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, BlindBoxItemWeight> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<BlindBoxItemWeight> DataList => _dataList;

    public BlindBoxItemWeight GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BlindBoxItemWeight Get(int key) => _dataMap[key];
    public BlindBoxItemWeight this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

