
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbBlindBox
{
    private readonly System.Collections.Generic.Dictionary<int, BlindBox> _dataMap;
    private readonly System.Collections.Generic.List<BlindBox> _dataList;
    
    public TbBlindBox(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BlindBox>(count);
        _dataList = new System.Collections.Generic.List<BlindBox>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BlindBox _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.BlindBox.DeserializeBlindBox(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, BlindBox> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<BlindBox> DataList => _dataList;

    public BlindBox GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BlindBox Get(int key) => _dataMap[key];
    public BlindBox this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

