
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbBlindBoxRevealPath
{
    private readonly System.Collections.Generic.Dictionary<int, BlindBoxRevealPath> _dataMap;
    private readonly System.Collections.Generic.List<BlindBoxRevealPath> _dataList;
    
    public TbBlindBoxRevealPath(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BlindBoxRevealPath>(count);
        _dataList = new System.Collections.Generic.List<BlindBoxRevealPath>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BlindBoxRevealPath _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.BlindBoxRevealPath.DeserializeBlindBoxRevealPath(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, BlindBoxRevealPath> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<BlindBoxRevealPath> DataList => _dataList;

    public BlindBoxRevealPath GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BlindBoxRevealPath Get(int key) => _dataMap[key];
    public BlindBoxRevealPath this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

