
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbDesktopActivityState
{
    private readonly System.Collections.Generic.Dictionary<int, DesktopActivityState> _dataMap;
    private readonly System.Collections.Generic.List<DesktopActivityState> _dataList;
    
    public TbDesktopActivityState(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, DesktopActivityState>(count);
        _dataList = new System.Collections.Generic.List<DesktopActivityState>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DesktopActivityState _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.DesktopActivityState.DeserializeDesktopActivityState(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, DesktopActivityState> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DesktopActivityState> DataList => _dataList;

    public DesktopActivityState GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DesktopActivityState Get(int key) => _dataMap[key];
    public DesktopActivityState this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

