
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbDogReaction
{
    private readonly System.Collections.Generic.Dictionary<int, DogReaction> _dataMap;
    private readonly System.Collections.Generic.List<DogReaction> _dataList;
    
    public TbDogReaction(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, DogReaction>(count);
        _dataList = new System.Collections.Generic.List<DogReaction>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DogReaction _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.DogReaction.DeserializeDogReaction(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, DogReaction> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DogReaction> DataList => _dataList;

    public DogReaction GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DogReaction Get(int key) => _dataMap[key];
    public DogReaction this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

