
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbEquipmentSlotConfig
{
    private readonly System.Collections.Generic.Dictionary<EItemType, EquipmentSlotConfig> _dataMap;
    private readonly System.Collections.Generic.List<EquipmentSlotConfig> _dataList;
    
    public TbEquipmentSlotConfig(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<EItemType, EquipmentSlotConfig>(count);
        _dataList = new System.Collections.Generic.List<EquipmentSlotConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EquipmentSlotConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.EquipmentSlotConfig.DeserializeEquipmentSlotConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemType, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<EItemType, EquipmentSlotConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<EquipmentSlotConfig> DataList => _dataList;

    public EquipmentSlotConfig GetOrDefault(EItemType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EquipmentSlotConfig Get(EItemType key) => _dataMap[key];
    public EquipmentSlotConfig this[EItemType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

