
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg
{
public partial class TbGameDevelopConfig
{
    private readonly System.Collections.Generic.Dictionary<bool, GameDevelopConfig> _dataMap;
    private readonly System.Collections.Generic.List<GameDevelopConfig> _dataList;
    
    public TbGameDevelopConfig(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<bool, GameDevelopConfig>(count);
        _dataList = new System.Collections.Generic.List<GameDevelopConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GameDevelopConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.GameDevelopConfig.DeserializeGameDevelopConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.IsSafeMode, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<bool, GameDevelopConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<GameDevelopConfig> DataList => _dataList;

    public GameDevelopConfig GetOrDefault(bool key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GameDevelopConfig Get(bool key) => _dataMap[key];
    public GameDevelopConfig this[bool key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

