
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbPlayerStatistic
{
    private readonly System.Collections.Generic.Dictionary<int, PlayerStatistic> _dataMap;
    private readonly System.Collections.Generic.List<PlayerStatistic> _dataList;
    
    public TbPlayerStatistic(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, PlayerStatistic>(count);
        _dataList = new System.Collections.Generic.List<PlayerStatistic>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PlayerStatistic _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.PlayerStatistic.DeserializePlayerStatistic(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.StatisticId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, PlayerStatistic> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PlayerStatistic> DataList => _dataList;

    public PlayerStatistic GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PlayerStatistic Get(int key) => _dataMap[key];
    public PlayerStatistic this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

