
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbSteamItemDef
{
    private readonly System.Collections.Generic.Dictionary<int, SteamItemDef> _dataMap;
    private readonly System.Collections.Generic.List<SteamItemDef> _dataList;
    
    public TbSteamItemDef(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, SteamItemDef>(count);
        _dataList = new System.Collections.Generic.List<SteamItemDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SteamItemDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.SteamItemDef.DeserializeSteamItemDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, SteamItemDef> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<SteamItemDef> DataList => _dataList;

    public SteamItemDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SteamItemDef Get(int key) => _dataMap[key];
    public SteamItemDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

