
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbTabGroup
{
    private readonly System.Collections.Generic.Dictionary<int, TabGroup> _dataMap;
    private readonly System.Collections.Generic.List<TabGroup> _dataList;
    
    public TbTabGroup(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, TabGroup>(count);
        _dataList = new System.Collections.Generic.List<TabGroup>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TabGroup _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.TabGroup.DeserializeTabGroup(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, TabGroup> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<TabGroup> DataList => _dataList;

    public TabGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TabGroup Get(int key) => _dataMap[key];
    public TabGroup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

