
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class Achievement : Luban.BeanBase
{
    public Achievement(JSONNode _buf) 
    {
        { if(!_buf["AchievementId"].IsNumber) { throw new SerializationException(); }  AchievementId = _buf["AchievementId"]; }
        { if(!_buf["ApiName"].IsString) { throw new SerializationException(); }  ApiName = _buf["ApiName"]; }
    }

    public static Achievement DeserializeAchievement(JSONNode _buf)
    {
        return new Achievement(_buf);
    }

    public readonly int AchievementId;
    public readonly string ApiName;
   
    public const int __ID__ = -879479025;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AchievementId:" + AchievementId + ","
        + "ApiName:" + ApiName + ","
        + "}";
    }
}
}

