
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class BGMList : Luban.BeanBase
{
    public BGMList(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["VolumeDb"].IsNumber) { throw new SerializationException(); }  VolumeDb = _buf["VolumeDb"]; }
        { if(!_buf["Enabled"].IsBoolean) { throw new SerializationException(); }  Enabled = _buf["Enabled"]; }
        { if(!_buf["AudioPath"].IsString) { throw new SerializationException(); }  AudioPath = _buf["AudioPath"]; }
    }

    public static BGMList DeserializeBGMList(JSONNode _buf)
    {
        return new BGMList(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    /// <summary>
    /// 单曲音量补偿，默认 0；过响可填 -3、-6
    /// </summary>
    public readonly float VolumeDb;
    /// <summary>
    /// 用于新版本预留
    /// </summary>
    public readonly bool Enabled;
    public readonly string AudioPath;
   
    public const int __ID__ = 551850342;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "VolumeDb:" + VolumeDb + ","
        + "Enabled:" + Enabled + ","
        + "AudioPath:" + AudioPath + ","
        + "}";
    }
}
}

