
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class BlindBoxSchedule : Luban.BeanBase
{
    public BlindBoxSchedule(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["BlindBoxId"].IsNumber) { throw new SerializationException(); }  BlindBoxId = _buf["BlindBoxId"]; }
        { var __json0 = _buf["VoucherUpgradeBlindBoxIds"]; if(!__json0.IsArray) { throw new SerializationException(); } VoucherUpgradeBlindBoxIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  VoucherUpgradeBlindBoxIds.Add(__v0); }   }
        { if(!_buf["IsLoopTrack"].IsBoolean) { throw new SerializationException(); }  IsLoopTrack = _buf["IsLoopTrack"]; }
        { if(!_buf["StartSeconds"].IsNumber) { throw new SerializationException(); }  StartSeconds = _buf["StartSeconds"]; }
        { if(!_buf["IntervalSeconds"].IsNumber) { throw new SerializationException(); }  IntervalSeconds = _buf["IntervalSeconds"]; }
        { if(!_buf["EndSeconds"].IsNumber) { throw new SerializationException(); }  EndSeconds = _buf["EndSeconds"]; }
        { if(!_buf["MaxGrantCount"].IsNumber) { throw new SerializationException(); }  MaxGrantCount = _buf["MaxGrantCount"]; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
        { if(!_buf["SteamPlaytimeGeneratorItemDefId"].IsNumber) { throw new SerializationException(); }  SteamPlaytimeGeneratorItemDefId = _buf["SteamPlaytimeGeneratorItemDefId"]; }
        { if(!_buf["SteamDropWindowSeconds"].IsNumber) { throw new SerializationException(); }  SteamDropWindowSeconds = _buf["SteamDropWindowSeconds"]; }
        { if(!_buf["SteamDropMaxPerWindow"].IsNumber) { throw new SerializationException(); }  SteamDropMaxPerWindow = _buf["SteamDropMaxPerWindow"]; }
    }

    public static BlindBoxSchedule DeserializeBlindBoxSchedule(JSONNode _buf)
    {
        return new BlindBoxSchedule(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 对应 BlindBox.Id
    /// </summary>
    public readonly int BlindBoxId;
    /// <summary>
    /// 按优先级填写可使用票券升级为的 BlindBox.Id。展示本行盲盒时，客户端按列表顺序检查对应盲盒的开箱票券，首个票券充足的盲盒将替代本行配置的 BlindBoxId；均不可用时仍展示原盲盒。留空表示不允许升级。
    /// </summary>
    public readonly System.Collections.Generic.List<int> VoucherUpgradeBlindBoxIds;
    /// <summary>
    /// TRUE 表示正常阶段循环装扮券生产行
    /// </summary>
    public readonly bool IsLoopTrack;
    /// <summary>
    /// 按玩家调度时钟计算的最早生效时间
    /// </summary>
    public readonly int StartSeconds;
    /// <summary>
    /// 非循环行为相对上次领取间隔；循环行为 Steam 装扮券掉落间隔
    /// </summary>
    public readonly int IntervalSeconds;
    /// <summary>
    /// 结束时间；无限循环填 -1
    /// </summary>
    public readonly int EndSeconds;
    /// <summary>
    /// 最多发放次数；不限填 -1
    /// </summary>
    public readonly int MaxGrantCount;
    /// <summary>
    /// 是否启用
    /// </summary>
    public readonly bool IsEnabled;
    /// <summary>
    /// 通过 TriggerItemDrop 请求的 Steam PlaytimeGenerator ItemDef ID；本地消耗品填 0
    /// </summary>
    public readonly int SteamPlaytimeGeneratorItemDefId;
    /// <summary>
    /// Steam 掉落窗口基础秒数；乘等待倍率后转为分钟；0 表示不启用
    /// </summary>
    public readonly int SteamDropWindowSeconds;
    /// <summary>
    /// Steam 掉落窗口内最多发放次数；未启用窗口时填 0
    /// </summary>
    public readonly int SteamDropMaxPerWindow;
   
    public const int __ID__ = -621265139;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BlindBoxId:" + BlindBoxId + ","
        + "VoucherUpgradeBlindBoxIds:" + Luban.StringUtil.CollectionToString(VoucherUpgradeBlindBoxIds) + ","
        + "IsLoopTrack:" + IsLoopTrack + ","
        + "StartSeconds:" + StartSeconds + ","
        + "IntervalSeconds:" + IntervalSeconds + ","
        + "EndSeconds:" + EndSeconds + ","
        + "MaxGrantCount:" + MaxGrantCount + ","
        + "IsEnabled:" + IsEnabled + ","
        + "SteamPlaytimeGeneratorItemDefId:" + SteamPlaytimeGeneratorItemDefId + ","
        + "SteamDropWindowSeconds:" + SteamDropWindowSeconds + ","
        + "SteamDropMaxPerWindow:" + SteamDropMaxPerWindow + ","
        + "}";
    }
}
}

