
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class DesktopActivityState : Luban.BeanBase
{
    public DesktopActivityState(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["StateName"].IsString) { throw new SerializationException(); }  StateName = _buf["StateName"]; }
        { if(!_buf["MinInputEventsPerMinute"].IsNumber) { throw new SerializationException(); }  MinInputEventsPerMinute = _buf["MinInputEventsPerMinute"]; }
        { if(!_buf["MaxInputEventsPerMinute"].IsNumber) { throw new SerializationException(); }  MaxInputEventsPerMinute = _buf["MaxInputEventsPerMinute"]; }
        { if(!_buf["MinDurationSeconds"].IsNumber) { throw new SerializationException(); }  MinDurationSeconds = _buf["MinDurationSeconds"]; }
        { if(!_buf["CooldownSeconds"].IsNumber) { throw new SerializationException(); }  CooldownSeconds = _buf["CooldownSeconds"]; }
        { if(!_buf["DogReactionTrigger"].IsNumber) { throw new SerializationException(); }  DogReactionTrigger = (EDogReactionTrigger)_buf["DogReactionTrigger"].AsInt; }
        { if(!_buf["EnableTongueFeedback"].IsBoolean) { throw new SerializationException(); }  EnableTongueFeedback = _buf["EnableTongueFeedback"]; }
        { if(!_buf["Priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["Priority"]; }
        { if(!_buf["Notes"].IsString) { throw new SerializationException(); }  Notes = _buf["Notes"]; }
    }

    public static DesktopActivityState DeserializeDesktopActivityState(JSONNode _buf)
    {
        return new DesktopActivityState(_buf);
    }

    /// <summary>
    /// 行 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 状态名，给人看的
    /// </summary>
    public readonly string StateName;
    /// <summary>
    /// 最近一段时间估算输入频率下限
    /// </summary>
    public readonly int MinInputEventsPerMinute;
    /// <summary>
    /// 输入频率上限，0表示无上限
    /// </summary>
    public readonly int MaxInputEventsPerMinute;
    /// <summary>
    /// 连续满足多久后才切换到该状态，防抖动
    /// </summary>
    public readonly float MinDurationSeconds;
    /// <summary>
    /// 切换到该状态后至少保持多久
    /// </summary>
    public readonly float CooldownSeconds;
    /// <summary>
    /// 要播放的狗狗表现
    /// </summary>
    public readonly EDogReactionTrigger DogReactionTrigger;
    /// <summary>
    /// 该状态下是否启用吐舌反馈
    /// </summary>
    public readonly bool EnableTongueFeedback;
    /// <summary>
    /// 多条规则命中时用，数字越大优先级越高
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Notes;
   
    public const int __ID__ = -1640672218;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "StateName:" + StateName + ","
        + "MinInputEventsPerMinute:" + MinInputEventsPerMinute + ","
        + "MaxInputEventsPerMinute:" + MaxInputEventsPerMinute + ","
        + "MinDurationSeconds:" + MinDurationSeconds + ","
        + "CooldownSeconds:" + CooldownSeconds + ","
        + "DogReactionTrigger:" + DogReactionTrigger + ","
        + "EnableTongueFeedback:" + EnableTongueFeedback + ","
        + "Priority:" + Priority + ","
        + "Notes:" + Notes + ","
        + "}";
    }
}
}

