
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class DogSkin : Luban.BeanBase
{
    public DogSkin(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["IconName"].IsString) { throw new SerializationException(); }  IconName = _buf["IconName"]; }
        { if(!_buf["DefaultEars"].IsString) { throw new SerializationException(); }  DefaultEars = _buf["DefaultEars"]; }
        { if(!_buf["DefaultEyes"].IsString) { throw new SerializationException(); }  DefaultEyes = _buf["DefaultEyes"]; }
        { if(!_buf["DefaultTongue"].IsString) { throw new SerializationException(); }  DefaultTongue = _buf["DefaultTongue"]; }
        { if(!_buf["FolderPath"].IsString) { throw new SerializationException(); }  FolderPath = _buf["FolderPath"]; }
        { if(!_buf["Head"].IsString) { throw new SerializationException(); }  Head = _buf["Head"]; }
        { if(!_buf["Claw_Left_Back"].IsString) { throw new SerializationException(); }  ClawLeftBack = _buf["Claw_Left_Back"]; }
        { if(!_buf["Claw_Right_Palms"].IsString) { throw new SerializationException(); }  ClawRightPalms = _buf["Claw_Right_Palms"]; }
        { if(!_buf["Tongue_Regular"].IsString) { throw new SerializationException(); }  TongueRegular = _buf["Tongue_Regular"]; }
        { if(!_buf["Ears_Happy"].IsString) { throw new SerializationException(); }  EarsHappy = _buf["Ears_Happy"]; }
        { if(!_buf["Ears_Plane"].IsString) { throw new SerializationException(); }  EarsPlane = _buf["Ears_Plane"]; }
        { if(!_buf["Eyes_Bored"].IsString) { throw new SerializationException(); }  EyesBored = _buf["Eyes_Bored"]; }
        { if(!_buf["Eyes_Cute"].IsString) { throw new SerializationException(); }  EyesCute = _buf["Eyes_Cute"]; }
        { if(!_buf["Eyes_Happy"].IsString) { throw new SerializationException(); }  EyesHappy = _buf["Eyes_Happy"]; }
        { if(!_buf["Eyes_Lucky"].IsString) { throw new SerializationException(); }  EyesLucky = _buf["Eyes_Lucky"]; }
        { if(!_buf["Eyes_Neutral"].IsString) { throw new SerializationException(); }  EyesNeutral = _buf["Eyes_Neutral"]; }
        { if(!_buf["Eyes_Wink"].IsString) { throw new SerializationException(); }  EyesWink = _buf["Eyes_Wink"]; }
    }

    public static DogSkin DeserializeDogSkin(JSONNode _buf)
    {
        return new DogSkin(_buf);
    }

    public readonly int Id;
    public readonly string IconName;
    /// <summary>
    /// 只影响图标和伪装模式，不影响打牌模式
    /// </summary>
    public readonly string DefaultEars;
    /// <summary>
    /// 只影响图标和伪装模式，不影响打牌模式
    /// </summary>
    public readonly string DefaultEyes;
    public readonly string DefaultTongue;
    public readonly string FolderPath;
    public readonly string Head;
    public readonly string ClawLeftBack;
    public readonly string ClawRightPalms;
    public readonly string TongueRegular;
    public readonly string EarsHappy;
    public readonly string EarsPlane;
    public readonly string EyesBored;
    public readonly string EyesCute;
    public readonly string EyesHappy;
    public readonly string EyesLucky;
    public readonly string EyesNeutral;
    public readonly string EyesWink;
   
    public const int __ID__ = -798721863;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "IconName:" + IconName + ","
        + "DefaultEars:" + DefaultEars + ","
        + "DefaultEyes:" + DefaultEyes + ","
        + "DefaultTongue:" + DefaultTongue + ","
        + "FolderPath:" + FolderPath + ","
        + "Head:" + Head + ","
        + "ClawLeftBack:" + ClawLeftBack + ","
        + "ClawRightPalms:" + ClawRightPalms + ","
        + "TongueRegular:" + TongueRegular + ","
        + "EarsHappy:" + EarsHappy + ","
        + "EarsPlane:" + EarsPlane + ","
        + "EyesBored:" + EyesBored + ","
        + "EyesCute:" + EyesCute + ","
        + "EyesHappy:" + EyesHappy + ","
        + "EyesLucky:" + EyesLucky + ","
        + "EyesNeutral:" + EyesNeutral + ","
        + "EyesWink:" + EyesWink + ","
        + "}";
    }
}
}

