
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 成就判定规则
    /// </summary>
    public enum EAchievementRuleType
    {
        /// <summary>
        /// 首次获得非初始道具部位
        /// </summary>
        FirstExternalItemType = 1,
        /// <summary>
        /// 首次获得非初始指定品质道具
        /// </summary>
        FirstExternalItemRarity = 2,
        /// <summary>
        /// 首次发生游戏事件
        /// </summary>
        FirstEvent = 3,
        /// <summary>
        /// 玩家统计达到数值
        /// </summary>
        StatisticAtLeast = 4,
    }

} 

