
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 投放类型
    /// </summary>
    public enum EAcquisitionType
    {
        /// <summary>
        /// 初始拥有
        /// </summary>
        Initial = 1,
        /// <summary>
        /// 装扮盲盒产出
        /// </summary>
        DecorationBlindBox = 2,
        /// <summary>
        /// 消耗品盲盒产出
        /// </summary>
        RefreshmentBlindBox = 3,
        /// <summary>
        /// 活动/LinkTree等
        /// </summary>
        EventReward = 4,
        /// <summary>
        /// 已下架
        /// </summary>
        Retired = 5,
        /// <summary>
        /// 仅调试
        /// </summary>
        DebugOnly = 6,
    }

} 

