
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 适用构建渠道
    /// </summary>
    [System.Flags]
    public enum EBuildChannelMask
    {
        /// <summary>
        /// 测试服
        /// </summary>
        Playtest = 2,
        /// <summary>
        /// 试玩版
        /// </summary>
        Demo = 4,
        /// <summary>
        /// 正式版
        /// </summary>
        Release = 8,
    }

} 

