
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 枚举类型
    /// </summary>
    public enum EEnumType
    {
        EDogAction = 0,
        GameState = 1,
        EHandRank = 2,
    }

} 

