
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// LinkTree 外部链接打开后的客户端侧校验方式
    /// </summary>
    public enum ELinkTreeOpenCheckType
    {
        /// <summary>
        /// 不做打开校验；通常只用于纯展示入口
        /// </summary>
        None = 0,
        /// <summary>
        /// OS.ShellOpen 返回 Error.Ok 后允许进入可领取状态
        /// </summary>
        ShellOpenOk = 1,
        /// <summary>
        /// 预留：确认 Steam 客户端或 Steam overlay 成功打开后允许领取
        /// </summary>
        SteamClientOk = 2,
        /// <summary>
        /// 预留：确认浏览器启动成功后允许领取
        /// </summary>
        BrowserProcessOk = 3,
    }

} 

