
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 幸运发牌模式
    /// </summary>
    public enum ELuckyDealMode
    {
        /// <summary>
        /// 当前模式：首轮保留赢家牌型线索；玩家换牌时优先获得补全目标牌型的牌。
        /// </summary>
        GuidedDraw = 1,
        /// <summary>
        /// 预留：直接发放完整赢家手牌。
        /// </summary>
        GuaranteedWin = 2,
        /// <summary>
        /// 预留：先发低赔率赢家牌，正确换牌后可升格到更高赔率牌型。
        /// </summary>
        BaitUpgrade = 3,
    }

} 

