
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 玩家统计单位
    /// </summary>
    public enum EPlayerStatisticUnit
    {
        /// <summary>
        /// 次数
        /// </summary>
        Count = 1,
        /// <summary>
        /// 筹码
        /// </summary>
        Chips = 2,
        /// <summary>
        /// 秒
        /// </summary>
        Seconds = 3,
    }

} 

