
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class EquipmentSlotConfig : Luban.BeanBase
{
    public EquipmentSlotConfig(JSONNode _buf) 
    {
        { if(!_buf["ItemType"].IsNumber) { throw new SerializationException(); }  ItemType = (EItemType)_buf["ItemType"].AsInt; }
        { if(!_buf["CanUnequip"].IsString) { throw new SerializationException(); }  CanUnequip = _buf["CanUnequip"]; }
        { if(!_buf["DefaultItemId"].IsNumber) { throw new SerializationException(); }  DefaultItemId = _buf["DefaultItemId"]; }
    }

    public static EquipmentSlotConfig DeserializeEquipmentSlotConfig(JSONNode _buf)
    {
        return new EquipmentSlotConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly EItemType ItemType;
    /// <summary>
    /// 可脱光吗
    /// </summary>
    public readonly string CanUnequip;
    /// <summary>
    /// 默认穿戴物品id
    /// </summary>
    public readonly int DefaultItemId;
   
    public const int __ID__ = 757388014;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemType:" + ItemType + ","
        + "CanUnequip:" + CanUnequip + ","
        + "DefaultItemId:" + DefaultItemId + ","
        + "}";
    }
}
}

