
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTables
{ 
    /// <summary>
    /// 奖励选择模式
    /// </summary>
    public enum ERewardSelectionMode
    {
        /// <summary>
        /// 按照 BlindBoxItemWeight 配置的权重抽取，允许重复获得此前抽中的物品。
        /// </summary>
        Normal = 1,
        /// <summary>
        /// 抽取时排除玩家此前从同一个盲盒中抽中的物品；其他盲盒抽中的同一道具不计入排除范围。（客户端盲盒专用，状态是否跨设备取决于云存档的最终设计）
        /// </summary>
        ExcludeDrawnInThisBox = 2,
    }

} 

