
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class GameDevelopConfig : Luban.BeanBase
{
    public GameDevelopConfig(JSONNode _buf) 
    {
        { if(!_buf["BlindBoxCostScale"].IsNumber) { throw new SerializationException(); }  BlindBoxCostScale = _buf["BlindBoxCostScale"]; }
        { if(!_buf["PlayerStatisticScale"].IsNumber) { throw new SerializationException(); }  PlayerStatisticScale = _buf["PlayerStatisticScale"]; }
        { if(!_buf["LinkTreeVisibleBannerCount"].IsNumber) { throw new SerializationException(); }  LinkTreeVisibleBannerCount = _buf["LinkTreeVisibleBannerCount"]; }
        { if(!_buf["SteamPlaytimeEligibilityLeadSeconds"].IsNumber) { throw new SerializationException(); }  SteamPlaytimeEligibilityLeadSeconds = _buf["SteamPlaytimeEligibilityLeadSeconds"]; }
    }

    public static GameDevelopConfig DeserializeGameDevelopConfig(JSONNode _buf)
    {
        return new GameDevelopConfig(_buf);
    }

    /// <summary>
    /// 盲盒消耗倍率
    /// </summary>
    public readonly float BlindBoxCostScale;
    /// <summary>
    /// 统计倍率
    /// </summary>
    public readonly float PlayerStatisticScale;
    /// <summary>
    /// LinkTree最佳显示条目数量
    /// </summary>
    public readonly int LinkTreeVisibleBannerCount;
    /// <summary>
    /// Steam资格提前真实秒数
    /// </summary>
    public readonly int SteamPlaytimeEligibilityLeadSeconds;
   
    public const int __ID__ = -780791539;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BlindBoxCostScale:" + BlindBoxCostScale + ","
        + "PlayerStatisticScale:" + PlayerStatisticScale + ","
        + "LinkTreeVisibleBannerCount:" + LinkTreeVisibleBannerCount + ","
        + "SteamPlaytimeEligibilityLeadSeconds:" + SteamPlaytimeEligibilityLeadSeconds + ","
        + "}";
    }
}
}

