
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class GameDevelopConfig : Luban.BeanBase
{
    public GameDevelopConfig(JSONNode _buf) 
    {
        { if(!_buf["BlindBoxTimeScale"].IsNumber) { throw new SerializationException(); }  BlindBoxTimeScale = _buf["BlindBoxTimeScale"]; }
        { if(!_buf["BlindBoxCostScale"].IsNumber) { throw new SerializationException(); }  BlindBoxCostScale = _buf["BlindBoxCostScale"]; }
    }

    public static GameDevelopConfig DeserializeGameDevelopConfig(JSONNode _buf)
    {
        return new GameDevelopConfig(_buf);
    }

    /// <summary>
    /// 等待盲盒时间倍率
    /// </summary>
    public readonly float BlindBoxTimeScale;
    /// <summary>
    /// 盲盒消耗倍率
    /// </summary>
    public readonly float BlindBoxCostScale;
   
    public const int __ID__ = -780791539;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BlindBoxTimeScale:" + BlindBoxTimeScale + ","
        + "BlindBoxCostScale:" + BlindBoxCostScale + ","
        + "}";
    }
}
}

