
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class LinkTree : Luban.BeanBase
{
    public LinkTree(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Key"].IsString) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["SortOrder"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["SortOrder"]; }
        { if(!_buf["IsPinned"].IsBoolean) { throw new SerializationException(); }  IsPinned = _buf["IsPinned"]; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
        { if(!_buf["TooltipKey"].IsString) { throw new SerializationException(); }  TooltipKey = _buf["TooltipKey"]; }
        { if(!_buf["BannerTexturePath"].IsString) { throw new SerializationException(); }  BannerTexturePath = _buf["BannerTexturePath"]; }
        { if(!_buf["BadgeTexturePath"].IsString) { throw new SerializationException(); }  BadgeTexturePath = _buf["BadgeTexturePath"]; }
        { if(!_buf["PreClaimUrl"].IsString) { throw new SerializationException(); }  PreClaimUrl = _buf["PreClaimUrl"]; }
        { if(!_buf["PostClaimUrl"].IsString) { throw new SerializationException(); }  PostClaimUrl = _buf["PostClaimUrl"]; }
        { if(!_buf["OpenCheckType"].IsNumber) { throw new SerializationException(); }  OpenCheckType = (ELinkTreeOpenCheckType)_buf["OpenCheckType"].AsInt; }
        { if(!_buf["RewardType"].IsNumber) { throw new SerializationException(); }  RewardType = (ELinkTreeRewardType)_buf["RewardType"].AsInt; }
        { if(!_buf["RewardItemId"].IsNumber) { throw new SerializationException(); }  RewardItemId = _buf["RewardItemId"]; }
        { if(!_buf["RewardChips"].IsNumber) { throw new SerializationException(); }  RewardChips = _buf["RewardChips"]; }
        { if(!_buf["SequentialPackId"].IsNumber) { throw new SerializationException(); }  SequentialPackId = _buf["SequentialPackId"]; }
        { if(!_buf["SteamPromoItemDefId"].IsNumber) { throw new SerializationException(); }  SteamPromoItemDefId = _buf["SteamPromoItemDefId"]; }
    }

    public static LinkTree DeserializeLinkTree(JSONNode _buf)
    {
        return new LinkTree(_buf);
    }

    /// <summary>
    /// 唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 稳定机器名，代码和存档/Steam 记录用，不要随意改名
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 显示顺序，数字越小越靠前
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 该值为TRUE 的条目始终参与 LinkTree 展示，不因奖励已领取而被替换，并优先占用展示位置
    /// </summary>
    public readonly bool IsPinned;
    /// <summary>
    /// 是否显示这个入口
    /// </summary>
    public readonly bool IsEnabled;
    /// <summary>
    /// Tooltip 本地化 key；当前也可直接作为显示名来源
    /// </summary>
    public readonly string TooltipKey;
    /// <summary>
    /// Banner 图片路径；可填 res:// 或项目相对路径
    /// </summary>
    public readonly string BannerTexturePath;
    /// <summary>
    /// 角标图片路径；空则使用默认礼物角标
    /// </summary>
    public readonly string BadgeTexturePath;
    /// <summary>
    /// 领奖前点击打开的外部链接，可带 UTM
    /// </summary>
    public readonly string PreClaimUrl;
    /// <summary>
    /// 领奖后点击打开的外部链接，可带 UTM
    /// </summary>
    public readonly string PostClaimUrl;
    /// <summary>
    /// 打开校验方式；当前合法值见 ELinkTreeOpenCheckType
    /// </summary>
    public readonly ELinkTreeOpenCheckType OpenCheckType;
    /// <summary>
    /// 奖励类型；当前合法值见 ELinkTreeRewardType
    /// </summary>
    public readonly ELinkTreeRewardType RewardType;
    /// <summary>
    /// RewardType=FixedItem 时发放的 Item.Id；不用填 0
    /// </summary>
    public readonly int RewardItemId;
    /// <summary>
    /// RewardType=FixedChips 时发放的固定筹码数；不用填 0
    /// </summary>
    public readonly int RewardChips;
    /// <summary>
    /// RewardType=SequentialPack 时关联的顺序礼包 ID；当前不用填 0
    /// </summary>
    public readonly int SequentialPackId;
    /// <summary>
    /// 未来 Steam 库存发奖/领取标记的 itemdef id；当前填 0
    /// </summary>
    public readonly int SteamPromoItemDefId;
   
    public const int __ID__ = 1258843864;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Key:" + Key + ","
        + "SortOrder:" + SortOrder + ","
        + "IsPinned:" + IsPinned + ","
        + "IsEnabled:" + IsEnabled + ","
        + "TooltipKey:" + TooltipKey + ","
        + "BannerTexturePath:" + BannerTexturePath + ","
        + "BadgeTexturePath:" + BadgeTexturePath + ","
        + "PreClaimUrl:" + PreClaimUrl + ","
        + "PostClaimUrl:" + PostClaimUrl + ","
        + "OpenCheckType:" + OpenCheckType + ","
        + "RewardType:" + RewardType + ","
        + "RewardItemId:" + RewardItemId + ","
        + "RewardChips:" + RewardChips + ","
        + "SequentialPackId:" + SequentialPackId + ","
        + "SteamPromoItemDefId:" + SteamPromoItemDefId + ","
        + "}";
    }
}
}

