
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class PayTable : Luban.BeanBase
{
    public PayTable(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["PayoutMultiplier"].IsNumber) { throw new SerializationException(); }  PayoutMultiplier = _buf["PayoutMultiplier"]; }
        { if(!_buf["HandRank"].IsNumber) { throw new SerializationException(); }  HandRank = (EHandRank)_buf["HandRank"].AsInt; }
        { if(!_buf["OriginalName"].IsString) { throw new SerializationException(); }  OriginalName = _buf["OriginalName"]; }
        { if(!_buf["SafeName_EN"].IsString) { throw new SerializationException(); }  SafeNameEN = _buf["SafeName_EN"]; }
        { if(!_buf["SafeName_CN"].IsString) { throw new SerializationException(); }  SafeNameCN = _buf["SafeName_CN"]; }
    }

    public static PayTable DeserializePayTable(JSONNode _buf)
    {
        return new PayTable(_buf);
    }

    public readonly int Id;
    public readonly int PayoutMultiplier;
    public readonly EHandRank HandRank;
    public readonly string OriginalName;
    public readonly string SafeNameEN;
    public readonly string SafeNameCN;
   
    public const int __ID__ = 1424107558;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PayoutMultiplier:" + PayoutMultiplier + ","
        + "HandRank:" + HandRank + ","
        + "OriginalName:" + OriginalName + ","
        + "SafeNameEN:" + SafeNameEN + ","
        + "SafeNameCN:" + SafeNameCN + ","
        + "}";
    }
}
}

