
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public sealed partial class SteamItemDef : Luban.BeanBase
{
    public SteamItemDef(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Key"].IsString) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = (ESteamItemDefType)_buf["Type"].AsInt; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["PromoRule"].IsString) { throw new SerializationException(); }  PromoRule = _buf["PromoRule"]; }
        { if(!_buf["GrantedManually"].IsBoolean) { throw new SerializationException(); }  GrantedManually = _buf["GrantedManually"]; }
        { if(!_buf["Tradable"].IsBoolean) { throw new SerializationException(); }  Tradable = _buf["Tradable"]; }
        { if(!_buf["Marketable"].IsBoolean) { throw new SerializationException(); }  Marketable = _buf["Marketable"]; }
        { if(!_buf["GameOnly"].IsBoolean) { throw new SerializationException(); }  GameOnly = _buf["GameOnly"]; }
        { if(!_buf["StoreHidden"].IsBoolean) { throw new SerializationException(); }  StoreHidden = _buf["StoreHidden"]; }
        { if(!_buf["AutoStack"].IsBoolean) { throw new SerializationException(); }  AutoStack = _buf["AutoStack"]; }
        { if(!_buf["Bundle"].IsString) { throw new SerializationException(); }  Bundle = _buf["Bundle"]; }
        { if(!_buf["IsEnabled"].IsBoolean) { throw new SerializationException(); }  IsEnabled = _buf["IsEnabled"]; }
    }

    public static SteamItemDef DeserializeSteamItemDef(JSONNode _buf)
    {
        return new SteamItemDef(_buf);
    }

    /// <summary>
    /// Steam Inventory 内唯一的 ItemDef ID；发布后不得改作他用
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 稳定机器名；发布后不要改名
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// Steam 定义类型；当前合法值见 ESteamItemDefType
    /// </summary>
    public readonly ESteamItemDefType Type;
    /// <summary>
    /// Steam 后台英文名称；game_only 回执不向玩家展示
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Steam 后台英文说明；game_only 回执不向玩家展示
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// Steam promo 属性；LinkTree 固定填 manual；补偿可填 owns:AppID<br/>只在“Steam 应该通过促销资格直接发放这个 ItemDef”时填写，其余时候留空
    /// </summary>
    public readonly string PromoRule;
    /// <summary>
    /// TRUE 时只能由 AddPromoItem/AddPromoItems 指定领取
    /// </summary>
    public readonly bool GrantedManually;
    /// <summary>
    /// 是否允许 Steam 交易
    /// </summary>
    public readonly bool Tradable;
    /// <summary>
    /// 是否允许 Steam 社区市场出售
    /// </summary>
    public readonly bool Marketable;
    /// <summary>
    /// TRUE 时不显示在 Steam 背包；回执和内部令牌填 TRUE
    /// </summary>
    public readonly bool GameOnly;
    /// <summary>
    /// TRUE 时不在 Steam 物品商店展示
    /// </summary>
    public readonly bool StoreHidden;
    /// <summary>
    /// 是否将同定义物品自动堆叠；一次性回执填 FALSE
    /// </summary>
    public readonly bool AutoStack;
    /// <summary>
    /// Bundle/Generator 的内容配方；普通 Item 留空
    /// </summary>
    public readonly string Bundle;
    /// <summary>
    /// 是否参与导出到 Steam ItemDef 配置
    /// </summary>
    public readonly bool IsEnabled;
   
    public const int __ID__ = -1587784542;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Key:" + Key + ","
        + "Type:" + Type + ","
        + "Name:" + Name + ","
        + "Description:" + Description + ","
        + "PromoRule:" + PromoRule + ","
        + "GrantedManually:" + GrantedManually + ","
        + "Tradable:" + Tradable + ","
        + "Marketable:" + Marketable + ","
        + "GameOnly:" + GameOnly + ","
        + "StoreHidden:" + StoreHidden + ","
        + "AutoStack:" + AutoStack + ","
        + "Bundle:" + Bundle + ","
        + "IsEnabled:" + IsEnabled + ","
        + "}";
    }
}
}

