
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbBGMList
{
    private readonly System.Collections.Generic.Dictionary<int, BGMList> _dataMap;
    private readonly System.Collections.Generic.List<BGMList> _dataList;
    
    public TbBGMList(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BGMList>(count);
        _dataList = new System.Collections.Generic.List<BGMList>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BGMList _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.BGMList.DeserializeBGMList(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, BGMList> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<BGMList> DataList => _dataList;

    public BGMList GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BGMList Get(int key) => _dataMap[key];
    public BGMList this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

