
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbBlindBoxRarityRate
{
    private readonly System.Collections.Generic.Dictionary<int, BlindBoxRarityRate> _dataMap;
    private readonly System.Collections.Generic.List<BlindBoxRarityRate> _dataList;
    
    public TbBlindBoxRarityRate(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BlindBoxRarityRate>(count);
        _dataList = new System.Collections.Generic.List<BlindBoxRarityRate>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BlindBoxRarityRate _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.BlindBoxRarityRate.DeserializeBlindBoxRarityRate(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, BlindBoxRarityRate> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<BlindBoxRarityRate> DataList => _dataList;

    public BlindBoxRarityRate GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BlindBoxRarityRate Get(int key) => _dataMap[key];
    public BlindBoxRarityRate this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

