
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbBlindBoxVisual
{
    private readonly System.Collections.Generic.Dictionary<int, BlindBoxVisual> _dataMap;
    private readonly System.Collections.Generic.List<BlindBoxVisual> _dataList;
    
    public TbBlindBoxVisual(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BlindBoxVisual>(count);
        _dataList = new System.Collections.Generic.List<BlindBoxVisual>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BlindBoxVisual _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.BlindBoxVisual.DeserializeBlindBoxVisual(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, BlindBoxVisual> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<BlindBoxVisual> DataList => _dataList;

    public BlindBoxVisual GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BlindBoxVisual Get(int key) => _dataMap[key];
    public BlindBoxVisual this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

