
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbBlindBoxSchedule
{
    private readonly System.Collections.Generic.Dictionary<int, BlindBoxSchedule> _dataMap;
    private readonly System.Collections.Generic.List<BlindBoxSchedule> _dataList;
    
    public TbBlindBoxSchedule(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BlindBoxSchedule>(count);
        _dataList = new System.Collections.Generic.List<BlindBoxSchedule>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BlindBoxSchedule _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.BlindBoxSchedule.DeserializeBlindBoxSchedule(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, BlindBoxSchedule> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<BlindBoxSchedule> DataList => _dataList;

    public BlindBoxSchedule GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BlindBoxSchedule Get(int key) => _dataMap[key];
    public BlindBoxSchedule this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

