
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbDogSkin
{
    private readonly System.Collections.Generic.Dictionary<int, DogSkin> _dataMap;
    private readonly System.Collections.Generic.List<DogSkin> _dataList;
    
    public TbDogSkin(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, DogSkin>(count);
        _dataList = new System.Collections.Generic.List<DogSkin>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DogSkin _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.DogSkin.DeserializeDogSkin(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, DogSkin> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DogSkin> DataList => _dataList;

    public DogSkin GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DogSkin Get(int key) => _dataMap[key];
    public DogSkin this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

