
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbInteractionHintConfig
{
    private readonly System.Collections.Generic.Dictionary<string, InteractionHintConfig> _dataMap;
    private readonly System.Collections.Generic.List<InteractionHintConfig> _dataList;
    
    public TbInteractionHintConfig(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, InteractionHintConfig>(count);
        _dataList = new System.Collections.Generic.List<InteractionHintConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            InteractionHintConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.InteractionHintConfig.DeserializeInteractionHintConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, InteractionHintConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<InteractionHintConfig> DataList => _dataList;

    public InteractionHintConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public InteractionHintConfig Get(string key) => _dataMap[key];
    public InteractionHintConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

