
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbLinkTree
{
    private readonly System.Collections.Generic.Dictionary<int, LinkTree> _dataMap;
    private readonly System.Collections.Generic.List<LinkTree> _dataList;
    
    public TbLinkTree(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, LinkTree>(count);
        _dataList = new System.Collections.Generic.List<LinkTree>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LinkTree _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.LinkTree.DeserializeLinkTree(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, LinkTree> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<LinkTree> DataList => _dataList;

    public LinkTree GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LinkTree Get(int key) => _dataMap[key];
    public LinkTree this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

