
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbRarityUI
{
    private readonly System.Collections.Generic.Dictionary<int, RarityUI> _dataMap;
    private readonly System.Collections.Generic.List<RarityUI> _dataList;
    
    public TbRarityUI(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, RarityUI>(count);
        _dataList = new System.Collections.Generic.List<RarityUI>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            RarityUI _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.RarityUI.DeserializeRarityUI(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, RarityUI> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<RarityUI> DataList => _dataList;

    public RarityUI GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RarityUI Get(int key) => _dataMap[key];
    public RarityUI this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

