
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace DataTables
{
public partial class TbSteamItemDefIdRange
{
    private readonly System.Collections.Generic.Dictionary<int, SteamItemDefIdRange> _dataMap;
    private readonly System.Collections.Generic.List<SteamItemDefIdRange> _dataList;
    
    public TbSteamItemDefIdRange(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, SteamItemDefIdRange>(count);
        _dataList = new System.Collections.Generic.List<SteamItemDefIdRange>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SteamItemDefIdRange _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::DataTables.SteamItemDefIdRange.DeserializeSteamItemDefIdRange(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, SteamItemDefIdRange> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<SteamItemDefIdRange> DataList => _dataList;

    public SteamItemDefIdRange GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SteamItemDefIdRange Get(int key) => _dataMap[key];
    public SteamItemDefIdRange this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

